---@class AIImplement
AIImplement = {} -- empty

function AIImplement.addAIFruitProhibitions() end
function AIImplement.addAIFruitRequirement() end
function AIImplement.addAITerrainDetailProhibitedRange() end
function AIImplement.addAITerrainDetailRequiredRange() end
function AIImplement.addVehicleToAIImplementList() end
function AIImplement.aiImplementEndLine() end
function AIImplement.aiImplementStartLine() end
function AIImplement.clearAIFruitProhibitions() end
function AIImplement.clearAIFruitRequirements() end
function AIImplement.clearAITerrainDetailProhibitedRange() end
function AIImplement.clearAITerrainDetailRequiredRange() end
function AIImplement.getAIAllowTurnBackward() end
function AIImplement.getAIBlockTurnBackward() end
function AIImplement.getAIFruitExtraRequirements() end
function AIImplement.getAIFruitProhibitions() end
function AIImplement.getAIFruitRequirements() end
function AIImplement.getAIHasNoFullCoverageArea() end
function AIImplement.getAIImplementCollisionTriggers() end
function AIImplement.getAIInvertMarkersOnTurn() end
function AIImplement.getAILookAheadSize() end
function AIImplement.getAILowerIfAnyIsLowered() end
function AIImplement.getAIMarkers() end
function AIImplement.getAIMinTurningRadius() end
function AIImplement.getAINeedsLowering() end
function AIImplement.getAISizeMarkers() end
function AIImplement.getAITerrainDetailProhibitedRange() end
function AIImplement.getAITerrainDetailRequiredRange() end
function AIImplement.getAIToolReverserDirectionNode() end
function AIImplement.getAITurnRadiusLimitation() end
function AIImplement.getAllowTireTracks() end
function AIImplement.getCanAIImplementContinueWork() end
function AIImplement.getCanImplementBeUsedForAI() end
function AIImplement.getDoConsumePtoPower() end
function AIImplement.getIsAIImplementInLine() end
function AIImplement.onLoad() end
function AIImplement.onPostLoad() end
function AIImplement.prerequisitesPresent() end
function AIImplement.registerEventListeners() end
function AIImplement.registerEvents() end
function AIImplement.registerFunctions() end
function AIImplement.registerOverwrittenFunctions() end
function AIImplement.setAIFruitExtraRequirements() end
function AIImplement.setAIFruitProhibitions() end
function AIImplement.setAIFruitRequirements() end
function AIImplement.setAIMarkersInverted() end
