---@class MathUtil
MathUtil = {} -- empty

function MathUtil.areaToHa() end
function MathUtil.bitsToMask() end
function MathUtil.clamp() end
function MathUtil.crossProduct() end
function MathUtil.daysToMs() end
function MathUtil.degToRad() end
function MathUtil.dotProduct() end
function MathUtil.getAngleDifference() end
function MathUtil.getBinary() end
function MathUtil.getBrightnessFromColor() end
function MathUtil.getCircleCircleIntersection() end
function MathUtil.getCircleLineIntersection() end
function MathUtil.getClosestPointOnLineSegment() end
function MathUtil.getDirectionFromYRotation() end
function MathUtil.getDistanceToRectangle2D() end
function MathUtil.getFlooredBounded() end
function MathUtil.getFlooredPercent() end
function MathUtil.getHasCircleLineIntersection() end
function MathUtil.getHaveLineSegementsIntersection2D() end
function MathUtil.getIsOutOfBounds() end
function MathUtil.getLineBoundingVolumeIntersect() end
function MathUtil.getLineLineIntersection2D() end
function MathUtil.getProjectOnLineParameter() end
function MathUtil.getRotationLimitedVector2() end
function MathUtil.getSignedDistanceToLineSegment2D() end
function MathUtil.getValidLimit() end
function MathUtil.getXZWidthAndHeight() end
function MathUtil.getYRotationFromDirection() end
function MathUtil.hasRectangleLineIntersection2D() end
function MathUtil.hasSphereSphereIntersection() end
function MathUtil.hoursToMs() end
function MathUtil.inchToM() end
function MathUtil.inverseLerp() end
function MathUtil.inverseVector3ArrayLerp() end
function MathUtil.inverseVector3Lerp() end
function MathUtil.isNan() end
function MathUtil.isPointInParallelogram() end
function MathUtil.kmhToMps() end
function MathUtil.lerp() end
function MathUtil.lerp3() end
function MathUtil.mToInch() end
function MathUtil.minutesToMs() end
function MathUtil.mpsToKmh() end
function MathUtil.msToDays() end
function MathUtil.msToHours() end
function MathUtil.msToMinutes() end
function MathUtil.nlerpQuaternionShortestPath() end
function MathUtil.normalizeRotationForShortestPath() end
function MathUtil.numberToSetBits() end
function MathUtil.numberToSetBitsStr() end
function MathUtil.projectOnLine() end
function MathUtil.quaternionMadShortestPath() end
function MathUtil.quaternionMult() end
function MathUtil.quaternionNormalized() end
function MathUtil.round() end
function MathUtil.rpmToMps() end
function MathUtil.sign() end
function MathUtil.slerpQuaternion() end
function MathUtil.slerpQuaternionShortestPath() end
function MathUtil.vector2Length() end
function MathUtil.vector2LengthSq() end
function MathUtil.vector2Normalize() end
function MathUtil.vector3ArrayLerp() end
function MathUtil.vector3Clamp() end
function MathUtil.vector3Length() end
function MathUtil.vector3LengthSq() end
function MathUtil.vector3Lerp() end
function MathUtil.vector3Normalize() end
function MathUtil.vector3SetLength() end
function MathUtil.vector3Transformation() end
