function Class() end
function InitClientOnce() end
function InitEventClass() end
function InitObjectClass() end
function InitStaticEventClass() end
function InitStaticObjectClass() end
function OnInGameMenuMenu() end
function OnLoadingScreen() end
function acceptedGameCreate() end
function acceptedGameInvite() end
function acceptedGameInvitePerformConnect() end
function addConsoleCommand() end
function addContactReport() end
function addDensityMapHeightAtWorldLine() end
function addDensityMapHeightAtWorldPos() end
function addDensityMapHeightOcclusionArea() end
function addDensityMapSyncerConnection() end
function addDensityMapSyncerDensityMap() end
function addDifferential() end
function addFeedingPlace() end
function addForce() end
function addHusbandryAnimal() end
function addImpulse() end
function addJointBreakReport() end
function addMilkingPlace() end
function addModEventListener() end
function addNotificationFilter() end
function addParticleSystemSimulationTime() end
function addReplacedCustomShader() end
function addSplitShapeConnection() end
function addSplitShapesShaderParameterOverwrite() end
function addTerrainDeformationArea() end
function addTerrainDeformationCircle() end
function addTerrainUpdateConnection() end
function addTimer() end
function addToPhysics() end
function addTorque() end
function addTorqueImpulse() end
function addTrackPoint() end
function addTrafficSystemPlayer() end
function addTrigger() end
function addVehicleLink() end
function addWakeUpReport() end
function aimCamera() end
function appIsSuspended() end
function applyTerrainDeformation() end
function areAchievementsAvailable() end
function areStatsAvailable() end
function asciiToUtf8() end
function assert() end
function assignAnimTrackClip() end
function autoStartLocalSavegame() end
function base64Decode() end
function base64Encode() end
function beginInputFuzzing() end
function bitAND() end
function bitHighestSet() end
function bitNOT() end
function bitOR() end
function bitShiftLeft() end
function bitShiftRight() end
function bitXOR() end
function buildNavMesh() end
function buildNavPath() end
function calcDistanceFrom() end
function calcDistanceSquaredFrom() end
function calculateFovY() end
function cancelAllStreamedI3DFiles() end
function cancelTerrainDeformation() end
function catmullRomInterpolator1() end
function catmullRomInterpolator3() end
function centerHeadTracking() end
function checkForNewDlcs() end
function cleanUpRenderingResources() end
function clearAnimTrackClip() end
function clearTerrainDeformationAreas() end
function clone() end
function cloneAnimCharacterSet() end
function closeIntervalTimer() end
function collectgarbage() end
function companionDebugDraw() end
function computeWheelShapeTireForces() end
function conditionalAnimationDebugDraw() end
function conditionalAnimationRegisterParameter() end
function conditionalAnimationZeroiseTrackTimes() end
function connectToServer() end
function consoleCommandChangeLanguage() end
function consoleCommandCleanI3DCache() end
function consoleCommandDrawGuiHelper() end
function consoleCommandDrawRawInput() end
function consoleCommandFuzzInput() end
function consoleCommandReloadCurrentGui() end
function consoleCommandSetDebugRenderingMode() end
function consoleCommandSetHighQuality() end
function consoleCommandShowSafeFrame() end
function consoleCommandSuspendApp() end
function consoleCommandToggleUiDebug() end
function consoleSetPowerConsumer() end
function consoleSetWiperState() end
function controlVehicle() end
function copyFile() end
function createAnimalCompanionManager() end
function createAnimalHusbandry() end
function createAudioSource() end
function createBitVectorMap() end
function createCCT() end
function createCamera() end
function createConditionalAnimation() end
function createDensityMapHeightUpdater() end
function createDensityMapSyncer() end
function createDensityMapVisualizationOverlay() end
function createFile() end
function createFillPlaneShape() end
function createFolder() end
function createFoliageBendingRectangle() end
function createFoliageBendingSystem() end
function createImageOverlay() end
function createImageOverlayWithTexture() end
function createLightSource() end
function createLowResCollisionHandler() end
function createNavMesh() end
function createNavPath() end
function createPedestrianSystem() end
function createRenderOverlay() end
function createReverbEffect() end
function createSample() end
function createSoundPlayer() end
function createStream() end
function createStreamedSample() end
function createTerrainDeformation() end
function createTerrainDetailUpdater() end
function createTerrainLayerTexture() end
function createTrack() end
function createTrafficSystem() end
function createTransformGroup() end
function createTyreTrackSystem() end
function createVideoOverlay() end
function createWebImageOverlay() end
function createWheelShape() end
function createXMLFile() end
function cutTrack() end
function delete() end
function deleteFile() end
function deleteFolder() end
function destroyFoliageBendingObject() end
function destroyLowResCollisionHandler() end
function destroyTrack() end
function disableAnimTrack() end
function doExit() end
function dofile() end
function draw() end
function drawDebugArrow() end
function drawDebugLine() end
function drawDebugPoint() end
function drawDebugTriangle() end
function enableAnimTrack() end
function enableDevelopmentControls() end
function enableTerrainDeformationMode() end
function enableTerrainDeformationPaintingMode() end
function enableTerrainDeformationSmoothingMode() end
function endFrameRepeatMode() end
function entityExists() end
function eraseParallelogram() end
function error() end
function executeSettingsChange() end
function exportScenegraphToGraphviz() end
function exportScenegraphToGraphvizRec() end
function extraUpdatePhysics() end
function fileExists() end
function fileWrite() end
function fillPlaneAdd() end
function filterText() end
function findAndRemoveSplitShapeAttachments() end
function findPolyline() end
function findSplitShape() end
function finishWriteSplitShapesServerEvents() end
function finishedUserProfileSync() end
function flushPhysicsCaches() end
function flushWebCache() end
function forceEndFrameRepeatMode() end
function gcinfo() end
function generateDensityMapVisualizationOverlay() end
function get4kAvailable() end
function getAchievement() end
function getAdaptiveVsync() end
function getAngularDamping() end
function getAngularVelocity() end
function getAnimCharacterSet() end
function getAnimClipDuration() end
function getAnimClipIndex() end
function getAnimNumOfClips() end
function getAnimTrackAssignedClip() end
function getAnimTrackBlendWeight() end
function getAnimTrackTime() end
function getAnimalCompanionNeedNetworkUpdate() end
function getAnimalFromCollisionNode() end
function getAnimalPosition() end
function getAnimalRotation() end
function getAnimalShaderParameter() end
function getAppBasePath() end
function getAtmosphereCornettAsymetryFactor() end
function getAtmosphereMieScale() end
function getAudioSourceAutoPlay() end
function getAudioSourceInnerRange() end
function getAudioSourceRange() end
function getAudioSourceSample() end
function getAudioSourceTickInaudible() end
function getAutoPerformanceClass() end
function getBitVectorMapNumChannels() end
function getBitVectorMapParallelogram() end
function getBitVectorMapPoint() end
function getBitVectorMapSize() end
function getBloomMagnitude() end
function getBloomMaskThreshold() end
function getBloomQuality() end
function getBrightness() end
function getCCTCollisionFlags() end
function getCamera() end
function getCanRenderUnicode() end
function getCenterOfMass() end
function getChild() end
function getChildAt() end
function getChildIndex() end
function getClipDistance() end
function getClipDistancesWithLOD() end
function getCloudQuality() end
function getCollisionMask() end
function getCompanionClosestDistance() end
function getConditionalAnimationBoolValue() end
function getConditionalAnimationFloatValue() end
function getCorrectTextSize() end
function getCropsGrowthNextState() end
function getCropsGrowthStateTime() end
function getCullOverride() end
function getCurrentMasterVolume() end
function getDate() end
function getDateAt() end
function getDateDiffSeconds() end
function getDebugRenderingMode() end
function getDensity() end
function getDensityAtWorldPos() end
function getDensityHeightAtWorldPos() end
function getDensityMapCollisionHeightAtWorldPos() end
function getDensityMapFilename() end
function getDensityMapHeightFirstChannel() end
function getDensityMapHeightNumChannels() end
function getDensityMapHeightTypeAtWorldLine() end
function getDensityMapHeightTypeAtWorldPos() end
function getDensityMapMaxHeight() end
function getDensityMapSize() end
function getDensityNormalAtWorldPos() end
function getDensityRegion() end
function getDensityRegionWorld() end
function getDiscretePerformanceSetting() end
function getDlcPath() end
function getDoFblendWeights() end
function getDoFparams() end
function getEffectiveClipDistancesWithLOD() end
function getEffectiveVisibility() end
function getEmitCountScale() end
function getEmitStartTime() end
function getEmitStopTime() end
function getEmitterShape() end
function getEmitterSurfaceSize() end
function getEngineRevision() end
function getExposureKeyValue() end
function getExposureRange() end
function getExposureTau() end
function getFarClip() end
function getFileIdHasSplitShapes() end
function getFileMD5() end
function getFiles() end
function getFillPlaneHeightAtLocalPos() end
function getFilterAnisotropy() end
function getFilterTrilinear() end
function getFogPlaneHeight() end
function getFogPlaneMieScale() end
function getFoliageViewDistance() end
function getFoliageViewDistanceCoeff() end
function getFovY() end
function getFullscreen() end
function getGPUDriverVersion() end
function getGPUName() end
function getGPUVendor() end
function getGameRevisionExtraText() end
function getGameTerritory() end
function getGamepadAxisLabel() end
function getGamepadAxisPhysicalName() end
function getGamepadButtonLabel() end
function getGamepadButtonPhysicalName() end
function getGamepadCategory() end
function getGamepadDefaultDeadzone() end
function getGamepadEnabled() end
function getGamepadId() end
function getGamepadMappedUnknownAxis() end
function getGamepadMappedUnknownButton() end
function getGamepadName() end
function getGamepadProductId() end
function getGamepadVendorId() end
function getGamepadVersionId() end
function getGamepadVibrationEnabled() end
function getGeometry() end
function getGravityDirection() end
function getHasClassId() end
function getHasGamepadAxis() end
function getHasGamepadButton() end
function getHasShaderParameter() end
function getHasShadowFocusBox() end
function getHasTerrainNormalMapping() end
function getHaveAchievementsChanged() end
function getHdrAvailable() end
function getHeadTrackingRotation() end
function getHeadTrackingTranslation() end
function getHeadTrackingType() end
function getHmdYaw() end
function getInputAxis() end
function getInputButton() end
function getIsBadUserReputation() end
function getIsCompound() end
function getIsCompoundChild() end
function getIsDensityMapVisualizationOverlayReady() end
function getIsGamepadMappingReliable() end
function getIsInCameraFrustum() end
function getIsLanguageEnabled() end
function getIsOrthographic() end
function getIsPhysicsUpdateIndexSimulated() end
function getIsSleeping() end
function getIsSoundPlayerChannelStreamed() end
function getIsSplitShapeSplit() end
function getIsValidModDir() end
function getKeyName() end
function getLODDistanceCoeff() end
function getLanguage() end
function getLanguageCode() end
function getLanguageName() end
function getLevenshteinDistance() end
function getLightColor() end
function getLightRange() end
function getLightScatteringDirection() end
function getLinearDamping() end
function getLinearVelocity() end
function getLoadNamedInterpolatorCurve() end
function getLocalLinearVelocity() end
function getMD5() end
function getMSAA() end
function getMass() end
function getMasterVolume() end
function getMaterial() end
function getMaxNumOfParticles() end
function getMaxNumShadowLights() end
function getMinClipDistance() end
function getModCategoryName() end
function getModDependency() end
function getModDownloadAvailability() end
function getModDownloadPath() end
function getModFreeSpaceKb() end
function getModHubRating() end
function getModId() end
function getModInstallPath() end
function getModMetaAttributeBool() end
function getModMetaAttributeInt() end
function getModMetaAttributeString() end
function getModNameAndBaseDirectory() end
function getModNumDependencies() end
function getModUseAvailability() end
function getModUsedSpaceKb() end
function getMoonBrightnessScale() end
function getMoonSizeScale() end
function getMotorRotationSpeed() end
function getMotorTorque() end
function getMouseButtonName() end
function getMultiplayerAvailability() end
function getNATType() end
function getName() end
function getNavMeshDistanceToWall() end
function getNavPathDirection() end
function getNavPathHasValidSlope() end
function getNavPathIsValid() end
function getNavPathLength() end
function getNavPathNumOfWaypoints() end
function getNavPathOrientation() end
function getNavPathPosition() end
function getNavPathWaypoint() end
function getNearClip() end
function getNeoMode() end
function getNetworkError() end
function getNormalizedScreenValues() end
function getNormalizedUVs() end
function getNormalizedValues() end
function getNotification() end
function getNumDlcPaths() end
function getNumMaterials() end
function getNumModCategories() end
function getNumOfChildren() end
function getNumOfContactReports() end
function getNumOfGamepads() end
function getNumOfLanguages() end
function getNumOfMods() end
function getNumOfNotifications() end
function getNumOfParticlesToEmitPerMs() end
function getNumOfProcessors() end
function getNumOfScreenModes() end
function getNumOfSplitShapes() end
function getNumOfTriggers() end
function getNumSoundPlayerChannels() end
function getNumSoundPlayerItems() end
function getOSVersionName() end
function getObjectMask() end
function getOrthographicHeight() end
function getOverallVisibility() end
function getP2PNodeId() end
function getParent() end
function getParticleSystemAverageSpeed() end
function getParticleSystemLifespan() end
function getParticleSystemNormalSpeed() end
function getParticleSystemSpeed() end
function getParticleSystemSpeedRandom() end
function getParticleSystemSpriteScaleX() end
function getParticleSystemSpriteScaleXGain() end
function getParticleSystemSpriteScaleY() end
function getParticleSystemSpriteScaleYGain() end
function getParticleSystemTangentSpeed() end
function getPedestrianSystemNightTimeRange() end
function getPerformanceClass() end
function getPerlinNoise2D() end
function getPhysicsDt() end
function getPhysicsDtNonInterpolated() end
function getPhysicsDtUnclamped() end
function getPhysicsUpdateIndex() end
function getProcessorFrequency() end
function getProcessorName() end
function getProjectionOffset() end
function getQuaternion() end
function getRandomPlayerColor() end
function getReflectionMapRatio() end
function getRenderDriver() end
function getResolutionScaling() end
function getRigidBodyType() end
function getRootNode() end
function getRotation() end
function getSSAOIntensity() end
function getSSAOQuality() end
function getSampleDuration() end
function getSamplePitch() end
function getSamplePlayOffset() end
function getSamplePlayTimeLeft() end
function getSampleVelocity() end
function getSampleVolume() end
function getScale() end
function getScreenAspectRatio() end
function getScreenHdrOutput() end
function getScreenMode() end
function getScreenModeInfo() end
function getShaderParameter() end
function getShaderQuality() end
function getShaderTimeSec() end
function getShadowMapFilterSize() end
function getShadowMapSize() end
function getShadowQuality() end
function getSoundPlayerChannelName() end
function getSoundPlayerItemName() end
function getSplineCV() end
function getSplineDirection() end
function getSplineLength() end
function getSplineNumOfCV() end
function getSplineOrientation() end
function getSplinePosition() end
function getSplitShapePlaneExtents() end
function getSplitShapeStats() end
function getSplitType() end
function getStartMode() end
function getStartParameters() end
function getStreamedSampleVolume() end
function getSunBrightnessScale() end
function getSunSizeScale() end
function getSystemLanguage() end
function getTerrainAttributesAtWorldPos() end
function getTerrainDeformationBlockedAreaMapSize() end
function getTerrainDetailByName() end
function getTerrainDetailName() end
function getTerrainDetailNumChannels() end
function getTerrainDetailViewDistance() end
function getTerrainHeightAtWorldPos() end
function getTerrainHeightMapFilename() end
function getTerrainLODDistanceCoeff() end
function getTerrainLayerAtWorldPos() end
function getTerrainLayerName() end
function getTerrainLayerNumOfSubLayers() end
function getTerrainLayerSubLayer() end
function getTerrainLodBlendDistances() end
function getTerrainLodBlendDynamicDistances() end
function getTerrainLodNormalMapFilename() end
function getTerrainLodTypeMapFilename() end
function getTerrainNormalAtWorldPos() end
function getTerrainNumOfLayers() end
function getTerrainSize() end
function getText3DHeight() end
function getText3DLength() end
function getText3DLineLength() end
function getText3DWidth() end
function getTextHeight() end
function getTextLength() end
function getTextLineLength() end
function getTextWidth() end
function getTextureResolution() end
function getTime() end
function getTimeSec() end
function getTotalSystemMemory() end
function getTrafficSystemNightTimeRange() end
function getTranslation() end
function getTyreTracksSegmentsCoeff() end
function getUniqueUserId() end
function getUseDoF() end
function getUseLightScattering() end
function getUserAttribute() end
function getUserId() end
function getUserName() end
function getUserProfileAppPath() end
function getVelocityAtLocalPos() end
function getVelocityAtWorldPos() end
function getVideoOverlayCurrentTime() end
function getVideoOverlayDuration() end
function getViewDistanceCoeff() end
function getVisibility() end
function getVolume() end
function getVolumeMeshTessellationCoeff() end
function getVsync() end
function getWheelShapeAxleSpeed() end
function getWheelShapeContactForce() end
function getWheelShapeContactNormal() end
function getWheelShapeContactObject() end
function getWheelShapeContactPoint() end
function getWheelShapePosition() end
function getWheelShapeSlip() end
function getWorldQuaternion() end
function getWorldRotation() end
function getWorldTranslation() end
function getXMLBool() end
function getXMLFloat() end
function getXMLInt() end
function getXMLRootName() end
function getXMLString() end
function getfenv() end
function getmetatable() end
function hasNativeAchievementGUI() end
function hasXMLProperty() end
function haveModsChanged() end
function hideAnimal() end
function imeAbort() end
function imeGetCursorPos() end
function imeGetLastString() end
function imeIsComplete() end
function imeIsOpen() end
function imeIsSupported() end
function imeOpen() end
function inAppFinishPendingPurchase() end
function inAppFinishPurchase() end
function inAppGetNumPendingPurchases() end
function inAppGetPendingPurchaseProductId() end
function inAppGetProductDescription() end
function inAppGetProductPrice() end
function inAppInit() end
function inAppIsLoaded() end
function inAppStartPurchase() end
function init() end
function initAchievements() end
function initConditionalAnimation() end
function initDensityMapHeightTypeProperties() end
function initModDownloadManager() end
function inspectTableAndPrint() end
function installMod() end
function ipairs() end
function is4kVideoMode() end
function isAbsolutPath() end
function isAnimTrackClipAssigned() end
function isAnimTrackEnabled() end
function isAnimalVisible() end
function isGameFullyInstalled() end
function isGamepadSigninPending() end
function isHeadTrackingAvailable() end
function isHusbandryReady() end
function isModUpdateRunning() end
function isSamplePlaying() end
function isSoundPlayerLoaded() end
function isSoundPlayerPlaying() end
function isUsingHmd() end
function isVideoOverlayPlaying() end
function keyEvent() end
function linearInterpolator1() end
function linearInterpolator2() end
function linearInterpolator3() end
function linearInterpolator4() end
function linearInterpolatorN() end
function linearInterpolatorTransRotScale() end
function link() end
function load() end
function loadAmbientSound() end
function loadBitVectorMapFromFile() end
function loadBitVectorMapNew() end
function loadCropsGrowthStateFromFile() end
function loadDlcs() end
function loadDlcsDirectories() end
function loadDlcsFromDirectory() end
function loadI3DFile() end
function loadInterpolator1Curve() end
function loadInterpolator2Curve() end
function loadInterpolator3Curve() end
function loadInterpolator4Curve() end
function loadLanguageSettings() end
function loadMod() end
function loadModDesc() end
function loadMods() end
function loadSample() end
function loadServerSettings() end
function loadSplitShapesFromFile() end
function loadStreamedSample() end
function loadTerrainDetailUpdaterStateFromFile() end
function loadUserSettings() end
function loadXMLFile() end
function loadXMLFileFromMemory() end
function loadfile() end
function loadstring() end
function localDirectionToLocal() end
function localDirectionToWorld() end
function localRotationToLocal() end
function localRotationToWorld() end
function localToLocal() end
function localToWorld() end
function log() end
function makeSplittable() end
function masterServerAddAvailableMod() end
function masterServerAddAvailableModEnd() end
function masterServerAddAvailableModStart() end
function masterServerAddDlc() end
function masterServerAddDlcEnd() end
function masterServerAddDlcStart() end
function masterServerAddServer() end
function masterServerAddServerMod() end
function masterServerAddServerModEnd() end
function masterServerAddServerModStart() end
function masterServerDisconnect() end
function masterServerInit() end
function masterServerReconnect() end
function masterServerRequestConnectionToServer() end
function masterServerRequestFilteredServers() end
function masterServerRequestServerDetails() end
function masterServerSetCallbacks() end
function masterServerSetNumPlayers() end
function masterServerSetServerInfo() end
function mathEulerRotateVector() end
function mathEulerToQuaternion() end
function mathQuaternionRotateVector() end
function meshNetworkAddNode() end
function meshNetworkBegin() end
function meshNetworkBeginConfig() end
function meshNetworkEnd() end
function meshNetworkEndConfig() end
function meshNetworkGetNodeStatusForApp() end
function modDownloadManagerLoaded() end
function modDownloadManagerUpdateSync() end
function mouseEvent() end
function moveCCT() end
function navMeshRaycast() end
function netCloseConnection() end
function netGetAndResetConnectionSendStats() end
function netGetBandwidthEstimate() end
function netGetConnectionStats() end
function netGetDefaultLocalIp() end
function netGetHostByAddr() end
function netGetTime() end
function netSendStream() end
function netSetIncomingPassword() end
function netSetIsEventProcessingEnabled() end
function netSetMaximumIncomingConnections() end
function netShutdown() end
function netStartup() end
function new2DLayer() end
function newproxy() end
function next() end
function nextMessageTypeId() end
function notificationsLoaded() end
function onBlockedListChanged() end
function onDeepLinkingFailed() end
function onFriendListChanged() end
function onOkSigninAccept() end
function onShowDeepLinkingErrorMsg() end
function openIntervalTimer() end
function openMpFriendInvitation() end
function openNativeHelpMenu() end
function openWebFile() end
function overlapBox() end
function overlapSphere() end
function pairs() end
function pauseSoundPlayer() end
function pauseStreamedSample() end
function pcall() end
function playSample() end
function playSoundPlayer() end
function playStreamedSample() end
function playVideoOverlay() end
function prepareSaveBitVectorMapToFile() end
function prepareSaveDensityMapToFile() end
function prepareSaveSplitShapesToFile() end
function prepareSaveTerrainHeightMap() end
function prepareSaveTerrainLodTypeMap() end
function prepareSplitShapesServerWriteUpdateStream() end
function print() end
function printCallstack() end
function printScenegraph() end
function printScenegraphRec() end
function printStatsOverlay() end
function print_r() end
function printf() end
function project() end
function projectToCamera() end
function promptUserConfirmScreenMode() end
function quaternionInterpolator() end
function quaternionInterpolator2() end
function rawequal() end
function rawget() end
function rawset() end
function raycastAll() end
function raycastClosest() end
function readAnimalCompanionManagerFromStream() end
function readBitVectorMapFromStream() end
function readDensityDataFromStream() end
function readDensityMapSyncerServerUpdateFromStream() end
function readIntervalTimerMs() end
function readSplitShapeIdFromStream() end
function readSplitShapesClientUpdateFromStream() end
function readSplitShapesFromStream() end
function readSplitShapesServerEventFromStream() end
function readSplitShapesServerUpdateFromStream() end
function readTerrainUpdateStream() end
function readTrafficSystemFromStream() end
function registerGlobalActionEvents() end
function registerHandTool() end
function registerObjectClassName() end
function reloadDlcsAndMods() end
function removeAllDifferentials() end
function removeCCT() end
function removeConsoleCommand() end
function removeContactReport() end
function removeDensityMapSyncerConnection() end
function removeFromPhysics() end
function removeHusbandryAnimal() end
function removeJoint() end
function removeJointBreakReport() end
function removeModEventListener() end
function removeSplitShapeAttachments() end
function removeSplitShapeConnection() end
function removeSplitShapesShaderParameterOverwrite() end
function removeTerrainUpdateConnection() end
function removeTimer() end
function removeTrafficSystemPlayer() end
function removeTrigger() end
function removeWakeUpReport() end
function removeXMLProperty() end
function render360Screenshot() end
function renderEnvProbe() end
function renderOverlay() end
function renderScreenshot() end
function renderText() end
function renderText3D() end
function replaceUnrenderableCharacters() end
function reportAnimalThreat() end
function requestExit() end
function requestGamepadSignin() end
function resetAutoExposure() end
function resetDensityMapVisualizationOverlay() end
function resetEmitStartTimer() end
function resetEmitStopTimer() end
function resetModOnCreateFunctions() end
function resetMultiplayerChecks() end
function resetNumOfEmittedParticles() end
function resetSplitShapes() end
function resetTrafficSystem() end
function restartApplication() end
function resumeStreamedSample() end
function rotate() end
function rotateAboutLocalAxis() end
function saveBitVectorMapToFile() end
function saveCancelUpdateList() end
function saveCropsGrowthStateToFile() end
function saveDeleteSavegame() end
function saveDensityMapToFile() end
function saveGetHasSpaceForSaveGame() end
function saveGetInfo() end
function saveGetInfoById() end
function saveGetNumOfSaveGames() end
function saveGetUploadState() end
function saveHardwareScalability() end
function savePreparedBitVectorMapToFile() end
function savePreparedDensityMapToFile() end
function savePreparedSplitShapesToFile() end
function savePreparedTerrainHeightMap() end
function savePreparedTerrainLodTypeMap() end
function saveReadSavegameCancel() end
function saveReadSavegameFinish() end
function saveReadSavegameGetProgress() end
function saveReadSavegameHasProgress() end
function saveReadSavegameStart() end
function saveResetStorageDeviceSelection() end
function saveResolveConflict() end
function saveScreenshot() end
function saveSetCloudErrorCallback() end
function saveSplitShapesToFile() end
function saveTerrainDetailUpdaterStateToFile() end
function saveTerrainHeightMap() end
function saveTerrainLodNormalMap() end
function saveTerrainLodTypeMap() end
function saveUpdateList() end
function saveWriteSavegameFinish() end
function saveWriteSavegameStart() end
function saveXMLFile() end
function saveXMLFileTo() end
function saveXMLFileToMemory() end
function searchText() end
function select() end
function setAdaptiveVsync() end
function setAngularDamping() end
function setAngularVelocity() end
function setAnimTrackBlendWeight() end
function setAnimTrackLoopState() end
function setAnimTrackSpeedScale() end
function setAnimTrackTime() end
function setAnimalDaytime() end
function setAnimalInteressNode() end
function setAnimalShaderParameter() end
function setAnimalTextureTile() end
function setAtmosphereCornettAsymetryFactor() end
function setAtmosphereMieScale() end
function setAtmosphereSecondaryLightSource() end
function setAudioCullingWorldProperties() end
function setAudioGroupVolume() end
function setAudioSourceAutoPlay() end
function setAudioSourceInnerRange() end
function setAudioSourceRange() end
function setAudioSourceTickInaudible() end
function setBitVectorMapParallelogram() end
function setBloomMagnitude() end
function setBloomMaskThreshold() end
function setBloomQuality() end
function setBrightness() end
function setCCTPosition() end
function setCamera() end
function setCaption() end
function setCenterOfMass() end
function setClipDistance() end
function setCloudFront() end
function setCloudQuality() end
function setCollisionMask() end
function setColorGradingSettings() end
function setCompanionArriveSteeringParameters() end
function setCompanionBehaviorIdleStay() end
function setCompanionBehaviorIdleWander() end
function setCompanionBehaviorWanderParameters() end
function setCompanionCommonSteeringParameters() end
function setCompanionDaytime() end
function setCompanionFeed() end
function setCompanionFetch() end
function setCompanionFollowEntity() end
function setCompanionGotoEntity() end
function setCompanionPet() end
function setCompanionPosition() end
function setCompanionSteeringTarget() end
function setCompanionSteeringWeights() end
function setCompanionThreat() end
function setCompanionTrigger() end
function setCompanionWanderSteeringParameters() end
function setCompanionWaterLevel() end
function setCompanionsPhysicsUpdate() end
function setCompanionsVisibility() end
function setConditionalAnimationBoolValue() end
function setConditionalAnimationFloatValue() end
function setConditionalAnimationSpecificParameterIds() end
function setCropsEnableGrowth() end
function setCropsGrowthMask() end
function setCropsGrowthNextState() end
function setCropsGrowthStateTime() end
function setCropsIgnoreDensityChanges() end
function setCropsMaxNumCellsPerFrame() end
function setCropsNumGrowthStates() end
function setCullOverride() end
function setCurrentMasterVolume() end
function setCurrentProcessPriority() end
function setDebugRenderingMode() end
function setDensityMapHeightCollisionMap() end
function setDensityMapHeightTypeProperties() end
function setDensityMapSyncerLostPacket() end
function setDensityMapVisualizationOverlayGrowthStateColor() end
function setDensityMapVisualizationOverlayStateBorderColor() end
function setDensityMapVisualizationOverlayStateColor() end
function setDensityMapVisualizationOverlayTypeColor() end
function setDensityMapVisualizationOverlayTypedStateColor() end
function setDensityMapVisualizationOverlayUpdateTimeLimit() end
function setDirection() end
function setDiscretePerformanceSetting() end
function setDoFblendWeights() end
function setDoFparams() end
function setDropCountScale() end
function setEmitCountScale() end
function setEmitStartTime() end
function setEmitStopTime() end
function setEmitterShape() end
function setEmittingState() end
function setEnableAmbientSound() end
function setEnableBetaMods() end
function setEnvMap() end
function setExposureKeyValue() end
function setExposureRange() end
function setExposureTau() end
function setFarClip() end
function setFileLogPrefixTimestamp() end
function setFillPlaneMaxPhysicalSurfaceAngle() end
function setFilterAnisotropy() end
function setFilterTrilinear() end
function setFogPlaneHeight() end
function setFogPlaneMieScale() end
function setFoliageBendingSystem() end
function setFoliageViewDistanceCoeff() end
function setFovY() end
function setFramerateLimiter() end
function setFrictionVelocity() end
function setFullscreen() end
function setGamepadDeadzone() end
function setGamepadDefaultDeadzone() end
function setGamepadDigitalOutput() end
function setGamepadEnabled() end
function setGamepadVibration() end
function setGamepadVibrationEnabled() end
function setGlobalCloudState() end
function setHasShadowFocusBox() end
function setHasTerrainNormalMapping() end
function setInvertStereoRendering() end
function setIsCompound() end
function setIsCompoundChild() end
function setIsOrthographic() end
function setJointDrive() end
function setJointFrame() end
function setJointPosition() end
function setJointRotationLimit() end
function setJointRotationLimitForceLimit() end
function setJointRotationLimitSpring() end
function setJointTranslationLimit() end
function setJointTranslationLimitForceLimit() end
function setJointTranslationLimitSpring() end
function setLODDistanceCoeff() end
function setLanguage() end
function setLightColor() end
function setLightCullingWorldProperties() end
function setLightRange() end
function setLightScatteringColor() end
function setLightScatteringDirection() end
function setLightShadowMap() end
function setLinearDamping() end
function setLinearVelocity() end
function setLowResCollisionHandlerTerrainRootNode() end
function setLuaErrorHandler() end
function setMSAA() end
function setMass() end
function setMasterVolume() end
function setMaterial() end
function setMaterialDiffuseMap() end
function setMaterialNormalMap() end
function setMaxNumOfParticles() end
function setMaxNumOfReflectionPlanes() end
function setMaxNumShadowLights() end
function setMilkingPlaceDoors() end
function setMinClipDistance() end
function setModDownloadManagerRecommenderParams() end
function setModHubRating() end
function setModInstalled() end
function setMoonBrightnessScale() end
function setMoonSizeScale() end
function setMotorProperties() end
function setName() end
function setNearClip() end
function setNumOfParticlesToEmitPerMs() end
function setObjectMask() end
function setOrthographicHeight() end
function setOverlayColor() end
function setOverlayLayer() end
function setOverlayRotation() end
function setOverlayUVs() end
function setPairCollision() end
function setParticleSystemLifespan() end
function setParticleSystemNormalSpeed() end
function setParticleSystemSpeed() end
function setParticleSystemSpeedRandom() end
function setParticleSystemSpriteScaleX() end
function setParticleSystemSpriteScaleXGain() end
function setParticleSystemSpriteScaleY() end
function setParticleSystemSpriteScaleYGain() end
function setParticleSystemTangentSpeed() end
function setParticleSystemTimeScale() end
function setPedestrianSystemDaytime() end
function setPedestrianSystemEnabled() end
function setPedestrianSystemNightTimeRange() end
function setPerformanceClass() end
function setPolylineTranslation() end
function setPresenceMode() end
function setProjectionOffset() end
function setQuaternion() end
function setReflectionMapObjectMasks() end
function setReflectionMapRatio() end
function setReflectionMapScaling() end
function setRenderOverlayAspectRatio() end
function setRenderOverlayCamera() end
function setResolutionScaling() end
function setRigidBodyType() end
function setRootNode() end
function setRotation() end
function setSSAOIntensity() end
function setSSAOQuality() end
function setSampleFrequencyFilter() end
function setSampleGroup() end
function setSamplePitch() end
function setSampleVelocity() end
function setSampleVolume() end
function setScale() end
function setSceneBrightness() end
function setScreenHdrOutput() end
function setScreenMode() end
function setShaderParameter() end
function setShaderQuality() end
function setShadowFocusBox() end
function setShadowMapFilterSize() end
function setShadowMapSize() end
function setShadowQuality() end
function setShapeCullingWorldProperties() end
function setSharedShaderParameter() end
function setShowMouseCursor() end
function setSolverIterationCount() end
function setSoundPlayerChannel() end
function setSoundPlayerItem() end
function setSplitShapesFileIdMapping() end
function setSplitShapesLoadingFileId() end
function setSplitShapesNextFileId() end
function setSplitShapesWorldCompressionParams() end
function setStartMode() end
function setStereoRendering() end
function setStreamLowPriorityI3DFiles() end
function setStreamedSampleGroup() end
function setStreamedSampleVolume() end
function setSunBrightnessScale() end
function setSunIsPrimary() end
function setSunSizeScale() end
function setTerrainDeformationBlockedAreaMap() end
function setTerrainDeformationBlockedAreaMaxDisplacement() end
function setTerrainDeformationDynamicObjectCollisionMask() end
function setTerrainDeformationDynamicObjectMaxDisplacement() end
function setTerrainDeformationOutsideAreaBrush() end
function setTerrainDeformationOutsideAreaConstraints() end
function setTerrainDeformationSmoothingAmount() end
function setTerrainHeightAtWorldPos() end
function setTerrainLODDistanceCoeff() end
function setTerrainLayerAtWorldPos() end
function setTerrainLoadDirectory() end
function setTerrainLodBlendDistances() end
function setTerrainLodBlendDynamicDistances() end
function setTextAlignment() end
function setTextBold() end
function setTextColor() end
function setTextDepthTestEnabled() end
function setTextLineBounds() end
function setTextLineHeightScale() end
function setTextRenderOverlay() end
function setTextVerticalAlignment() end
function setTextWidthScale() end
function setTextWrapWidth() end
function setTextureResolution() end
function setTimerTime() end
function setTrafficSystemDaytime() end
function setTrafficSystemEnabled() end
function setTrafficSystemNightTimeRange() end
function setTrafficSystemUseOutdoorAudioSetup() end
function setTranslation() end
function setTyreTracksSegementsCoeff() end
function setUpdateCycleTime() end
function setUpdateDeltaValue() end
function setUpdateMask() end
function setUpdateMaskFromInfoLayer() end
function setUpdateMinMaxValue() end
function setUseDoF() end
function setUseKinematicSplitShapes() end
function setUseLightScattering() end
function setUserAttribute() end
function setUserConfirmScreenMode() end
function setVideoOverlayPosition() end
function setVideoOverlayVolume() end
function setViewDistanceCoeff() end
function setViewport() end
function setVisibility() end
function setVolumeMeshTessellationCoeff() end
function setVsync() end
function setWheelShapeAutoHoldBrakeForce() end
function setWheelShapeDirection() end
function setWheelShapeForcePoint() end
function setWheelShapeProps() end
function setWheelShapeSteeringCenter() end
function setWheelShapeTireFriction() end
function setWheelShapeWidth() end
function setWindVelocity() end
function setWindowFocus() end
function setWorldQuaternion() end
function setWorldRotation() end
function setWorldTranslation() end
function setXMLBool() end
function setXMLFloat() end
function setXMLInt() end
function setXMLString() end
function setfenv() end
function setmetatable() end
function showAnimal() end
function showGameInstallProgress() end
function showSigninScreen() end
function showSoundPlayerContentRatingWarning() end
function showUserProfile() end
function simulateParticleSystems() end
function simulatePhysics() end
function simulatePhysicsTimeScale() end
function smoothDensityMapHeightAtWorldPos() end
function source() end
function splitShape() end
function startDevClient() end
function startDevServer() end
function startFrameRepeatMode() end
function startServerGame() end
function startUpdatePendingMods() end
function startWriteSplitShapesServerEvents() end
function statsGet() end
function statsGetIndex() end
function statsSet() end
function stopSample() end
function stopStreamedSample() end
function stopVideoOverlay() end
function storeAreDlcsCorrupted() end
function storeBeginUserSignIn() end
function storeGetBuyPageState() end
function storeGetNumProducts() end
function storeGetOnlineState() end
function storeGetProductInfo() end
function storeGetProductPrice() end
function storeHasNativeGUI() end
function storeHaveDlcsChanged() end
function storeOpenBuyPage() end
function storeRequestCloseBuyPage() end
function streamAlignReadToByteBoundary() end
function streamAlignWriteToByteBoundary() end
function streamGetIpAndPort() end
function streamGetNumOfUnreadBits() end
function streamGetReadOffset() end
function streamGetWriteOffset() end
function streamI3DFile() end
function streamReadBool() end
function streamReadFloat32() end
function streamReadInt16() end
function streamReadInt32() end
function streamReadInt8() end
function streamReadIntN() end
function streamReadManualTimestamp() end
function streamReadString() end
function streamReadUInt16() end
function streamReadUInt8() end
function streamReadUIntN() end
function streamSetReadOffset() end
function streamSetWriteOffset() end
function streamWriteBool() end
function streamWriteFloat32() end
function streamWriteInt16() end
function streamWriteInt32() end
function streamWriteInt8() end
function streamWriteIntN() end
function streamWriteManualTimestamp() end
function streamWriteStream() end
function streamWriteString() end
function streamWriteTimestamp() end
function streamWriteUInt16() end
function streamWriteUInt8() end
function streamWriteUIntN() end
function syncProfileFiles() end
function testSplitShape() end
function toggleShowFPS() end
function toggleStatsOverlay() end
function toggleVisibility() end
function tonumber() end
function tostring() end
function touchEvent() end
function traceOff() end
function traceOn() end
function translate() end
function type() end
function unProject() end
function unicodeToUtf8() end
function uninstallMod() end
function unlink() end
function unloadAmbientSound() end
function unlockAchievement() end
function unpack() end
function unregisterObjectClassName() end
function update() end
function updateAmbientSound() end
function updateAspectRatio() end
function updateConditionalAnimation() end
function updateDifferential() end
function updateFeedingPlace() end
function updateLoadingBar() end
function updateLoadingBarProgress() end
function updateMod() end
function updatePlacementCollisionMap() end
function updateRenderOverlay() end
function updateTerrainCollisionMap() end
function updateVideoOverlay() end
function upnpAddPortMapping() end
function upnpDiscover() end
function upnpRemovePortMapping() end
function usleep() end
function utf8Strlen() end
function utf8Substr() end
function utf8ToLower() end
function utf8ToUnicode() end
function utf8ToUpper() end
function verifyDlcs() end
function watchTable() end
function watchTableLive() end
function worldDirectionToLocal() end
function worldRotationToLocal() end
function worldToLocal() end
function wrapMousePosition() end
function writeAnimalCompanionManagerToStream() end
function writeBitVectorMapToStream() end
function writeDensityDataToStream() end
function writeDensityMapSyncerServerUpdateToStream() end
function writeSplitShapeIdToStream() end
function writeSplitShapesClientUpdateToStream() end
function writeSplitShapesServerEventToStream() end
function writeSplitShapesServerUpdateToStream() end
function writeSplitShapesToStream() end
function writeTerrainDeformationBlockedAreas() end
function writeTerrainUpdateStream() end
function writeTrafficSystemToStream() end
function xpcall() end
