---@class AnimalHusbandry
AnimalHusbandry = {
    GAME_LIMIT = 10,
    NO_FILLTYPE_INFOS = {
    },
    classId = 22,
    className = 'AnimalHusbandry',
}

function AnimalHusbandry.addAnimals() end
function AnimalHusbandry.addPendingAnimal() end
function AnimalHusbandry.addRideable() end
function AnimalHusbandry.addSingleAnimal() end
function AnimalHusbandry.canAddMoreHusbandriesToGame() end
function AnimalHusbandry.canBeSold() end
function AnimalHusbandry.canBuy() end
function AnimalHusbandry.class() end
function AnimalHusbandry.cleanAnimal() end
function AnimalHusbandry.collectPickObjects() end
function AnimalHusbandry.copy() end
function AnimalHusbandry.dayChanged() end
function AnimalHusbandry.delete() end
function AnimalHusbandry.finalizePlacement() end
function AnimalHusbandry.getAnimalName() end
function AnimalHusbandry.getAnimalSubTypeCount() end
function AnimalHusbandry.getAnimalType() end
function AnimalHusbandry.getAnimals() end
function AnimalHusbandry.getCanBePlacedAt() end
function AnimalHusbandry.getCanBeRidden() end
function AnimalHusbandry.getConsumedFood() end
function AnimalHusbandry.getFilltype() end
function AnimalHusbandry.getFluidStatsText() end
function AnimalHusbandry.getFoodFilltypeInfo() end
function AnimalHusbandry.getFoodProductionFactor() end
function AnimalHusbandry.getFoodSpillageFactor() end
function AnimalHusbandry.getGlobalDirtFactor() end
function AnimalHusbandry.getGlobalProductionFactor() end
function AnimalHusbandry.getHusbandryId() end
function AnimalHusbandry.getHusbandryModule() end
function AnimalHusbandry.getLiquidManureFilltypeInfo() end
function AnimalHusbandry.getManureFilltypeInfo() end
function AnimalHusbandry.getMaxNumAnimals() end
function AnimalHusbandry.getMilkFilltypeInfo() end
function AnimalHusbandry.getMinutesUntilNextAnimal() end
function AnimalHusbandry.getModuleById() end
function AnimalHusbandry.getModuleByName() end
function AnimalHusbandry.getNumOfAnimals() end
function AnimalHusbandry.getPalletsFilltypeInfo() end
function AnimalHusbandry.getProductionFilltypeInfo() end
function AnimalHusbandry.getReproductionTimePerDay() end
function AnimalHusbandry.getSpecValueAnimalFoodFillTypes() end
function AnimalHusbandry.getSpecValueNumberAnimals() end
function AnimalHusbandry.getStrawFilltypeInfo() end
function AnimalHusbandry.getSupportsRiding() end
function AnimalHusbandry.getSupportsSubType() end
function AnimalHusbandry.getTypedAnimals() end
function AnimalHusbandry.getWaterFilltypeInfo() end
function AnimalHusbandry.hasStraw() end
function AnimalHusbandry.hasWater() end
function AnimalHusbandry.hourChanged() end
function AnimalHusbandry.initPlaceableType() end
function AnimalHusbandry.isAnimalDirty() end
function AnimalHusbandry.isRideableInOnHusbandryGround() end
function AnimalHusbandry.isSimilarHusbandryRegistered() end
function AnimalHusbandry.isa() end
function AnimalHusbandry.load() end
function AnimalHusbandry.loadFromXMLFile() end
function AnimalHusbandry.loadModules() end
function AnimalHusbandry.loadSpecValueAnimalFoodFillTypes() end
function AnimalHusbandry.loadSpecValueNumberAnimals() end
function AnimalHusbandry.minuteChanged() end
function AnimalHusbandry.modulesFinalizePlacement() end
function AnimalHusbandry.new() end
function AnimalHusbandry.onIntervalModulesUpdate() end
function AnimalHusbandry.onSell() end
function AnimalHusbandry.readStream() end
function AnimalHusbandry.readUpdateStream() end
function AnimalHusbandry.registerHusbandryToMission() end
function AnimalHusbandry.removeAnimals() end
function AnimalHusbandry.removeRideable() end
function AnimalHusbandry.removeSingleAnimal() end
function AnimalHusbandry.renameAnimal() end
function AnimalHusbandry.saveToXMLFile() end
function AnimalHusbandry.setAnimalDirt() end
function AnimalHusbandry.setModuleParameters() end
function AnimalHusbandry.superClass() end
function AnimalHusbandry.unregisterHusbandryToMission() end
function AnimalHusbandry.update() end
function AnimalHusbandry.updateGlobalProductionFactor() end
function AnimalHusbandry.writeStream() end
function AnimalHusbandry.writeUpdateStream() end
