---@class Attachable
Attachable = {} -- empty

function Attachable.attachableAddToolCameras() end
function Attachable.attachableRemoveToolCameras() end
function Attachable.getActiveFarm() end
function Attachable.getActiveInputAttacherJoint() end
function Attachable.getActiveInputAttacherJointDescIndex() end
function Attachable.getAllowsLowering() end
function Attachable.getAttachbleAirConsumerUsage() end
function Attachable.getAttacherVehicle() end
function Attachable.getBrakeForce() end
function Attachable.getCanAIImplementContinueWork() end
function Attachable.getCanBeSelected() end
function Attachable.getCanToggleTurnedOn() end
function Attachable.getDeactivateOnLeave() end
function Attachable.getInputAttacherJointByJointDescIndex() end
function Attachable.getInputAttacherJoints() end
function Attachable.getIsActive() end
function Attachable.getIsAttachedTo() end
function Attachable.getIsFoldAllowed() end
function Attachable.getIsImplementChainLowered() end
function Attachable.getIsInUse() end
function Attachable.getIsInWorkPosition() end
function Attachable.getIsInputAttacherActive() end
function Attachable.getIsLowered() end
function Attachable.getIsOperating() end
function Attachable.getLoweringActionEventState() end
function Attachable.getOwner() end
function Attachable.getRootVehicle() end
function Attachable.getSteeringAxleBaseVehicle() end
function Attachable.initSpecialization() end
function Attachable.isDetachAllowed() end
function Attachable.loadInputAttacherJoint() end
function Attachable.mountDynamic() end
function Attachable.onAIImplementEndLine() end
function Attachable.onAIImplementStartLine() end
function Attachable.onDeactivate() end
function Attachable.onLoad() end
function Attachable.onPostLoad() end
function Attachable.onPreDelete() end
function Attachable.onReadStream() end
function Attachable.onSelect() end
function Attachable.onStateChange() end
function Attachable.onUnselect() end
function Attachable.onUpdate() end
function Attachable.onWriteStream() end
function Attachable.postAttach() end
function Attachable.postDetach() end
function Attachable.preAttach() end
function Attachable.preDetach() end
function Attachable.prerequisitesPresent() end
function Attachable.registerEventListeners() end
function Attachable.registerEvents() end
function Attachable.registerFunctions() end
function Attachable.registerLoweringActionEvent() end
function Attachable.registerOverwrittenFunctions() end
function Attachable.saveToXMLFile() end
function Attachable.setLowered() end
function Attachable.setLoweredAll() end
