---@class ButtonElement
ButtonElement = {} -- empty

function ButtonElement.applyButtonAspectScale() end
function ButtonElement.applyScreenAlignment() end
function ButtonElement.canReceiveFocus() end
function ButtonElement.class() end
function ButtonElement.copy() end
function ButtonElement.copyAttributes() end
function ButtonElement.delete() end
function ButtonElement.draw() end
function ButtonElement.getIconModifiedTextOffset() end
function ButtonElement.getIconOffset() end
function ButtonElement.getIconSize() end
function ButtonElement.getIsActive() end
function ButtonElement.getIsHighlighted() end
function ButtonElement.getIsSelected() end
function ButtonElement.getText2Offset() end
function ButtonElement.getTextOffset() end
function ButtonElement.isFocused() end
function ButtonElement.isa() end
function ButtonElement.keyEvent() end
function ButtonElement.loadFromXML() end
function ButtonElement.loadInputGlyph() end
function ButtonElement.loadInputGlyphColors() end
function ButtonElement.loadProfile() end
function ButtonElement.mouseEvent() end
function ButtonElement.new() end
function ButtonElement.onClose() end
function ButtonElement.onFocusActivate() end
function ButtonElement.onFocusEnter() end
function ButtonElement.onFocusLeave() end
function ButtonElement.onHighlight() end
function ButtonElement.onHighlightRemove() end
function ButtonElement.onOpen() end
function ButtonElement.reset() end
function ButtonElement.setAlpha() end
function ButtonElement.setClickSound() end
function ButtonElement.setDisabled() end
function ButtonElement.setIconSize() end
function ButtonElement.setImageFilename() end
function ButtonElement.setImageUVs() end
function ButtonElement.setInputAction() end
function ButtonElement.setKeyboardMode() end
function ButtonElement.setSelected() end
function ButtonElement.setText() end
function ButtonElement.setTextSize() end
function ButtonElement.superClass() end
function ButtonElement.updateSize() end
