---@class Combine
Combine = {
    DAMAGED_YIELD_REDUCTION = 0.4,
}

function Combine.actionEventToggleChopper() end
function Combine.addCutterArea() end
function Combine.addCutterToCombine() end
function Combine.getCanBeSelected() end
function Combine.getCanBeTurnedOn() end
function Combine.getCombineLoadPercentage() end
function Combine.getFillLevelDependentSpeed() end
function Combine.getIsBufferCombine() end
function Combine.getIsFoldAllowed() end
function Combine.getIsThreshingAllowed() end
function Combine.getTurnedOnNotAllowedWarning() end
function Combine.initSpecialization() end
function Combine.loadCombineEffects() end
function Combine.loadCombineRotationNodes() end
function Combine.loadCombineSamples() end
function Combine.loadCombineSetup() end
function Combine.loadWorkAreaFromXML() end
function Combine.onChangedFillType() end
function Combine.onDeactivate() end
function Combine.onDelete() end
function Combine.onDraw() end
function Combine.onEndWorkAreaProcessing() end
function Combine.onEnterVehicle() end
function Combine.onFillUnitFillLevelChanged() end
function Combine.onFoldStateChanged() end
function Combine.onLeaveVehicle() end
function Combine.onLoad() end
function Combine.onPostAttachImplement() end
function Combine.onPostDetachImplement() end
function Combine.onPostLoad() end
function Combine.onReadStream() end
function Combine.onReadUpdateStream() end
function Combine.onRegisterActionEvents() end
function Combine.onStartWorkAreaProcessing() end
function Combine.onTurnedOff() end
function Combine.onTurnedOn() end
function Combine.onUpdate() end
function Combine.onUpdateTick() end
function Combine.onWriteStream() end
function Combine.onWriteUpdateStream() end
function Combine.prerequisitesPresent() end
function Combine.processCombineChopperArea() end
function Combine.processCombineSwathArea() end
function Combine.registerEventListeners() end
function Combine.registerEvents() end
function Combine.registerFunctions() end
function Combine.registerOverwrittenFunctions() end
function Combine.removeCutterFromCombine() end
function Combine.saveToXMLFile() end
function Combine.setChopperPSEnabled() end
function Combine.setCombineIsFilling() end
function Combine.setIsSwathActive() end
function Combine.setStrawPSEnabled() end
function Combine.setWorkedHectars() end
function Combine.startThreshing() end
function Combine.stopThreshing() end
function Combine.updateToggleStrawText() end
function Combine.verifyCombine() end
