---@class Enterable
Enterable = {} -- empty

function Enterable.actionEventActivateObject() end
function Enterable.actionEventCameraSwitch() end
function Enterable.actionEventCameraZoomIn() end
function Enterable.actionEventCameraZoomOut() end
function Enterable.actionEventLeave() end
function Enterable.actionEventResetHeadTracking() end
function Enterable.addToolCameras() end
function Enterable.deleteVehicleCharacter() end
function Enterable.drawUIInfo() end
function Enterable.enterVehicle() end
function Enterable.getActiveCamera() end
function Enterable.getActiveFarm() end
function Enterable.getAllowCharacterVisibilityUpdate() end
function Enterable.getCanToggleAttach() end
function Enterable.getCanToggleSelectable() end
function Enterable.getControllerName() end
function Enterable.getCurrentPlayerStyle() end
function Enterable.getDisableVehicleCharacterOnLeave() end
function Enterable.getDistanceToNode() end
function Enterable.getExitNode() end
function Enterable.getFormattedOperatingTime() end
function Enterable.getInteractionHelp() end
function Enterable.getIsActive() end
function Enterable.getIsActiveForInput() end
function Enterable.getIsAdditionalCharacterActive() end
function Enterable.getIsControlled() end
function Enterable.getIsDashboardGroupActive() end
function Enterable.getIsEnterable() end
function Enterable.getIsEntered() end
function Enterable.getIsInUse() end
function Enterable.getIsTabbable() end
function Enterable.getPlayerColorIndex() end
function Enterable.getPlayerModelIndex() end
function Enterable.getUserPlayerStyle() end
function Enterable.getVehicleCharacter() end
function Enterable.interact() end
function Enterable.leaveVehicle() end
function Enterable.loadAdditionalCharacterFromXML() end
function Enterable.loadCamerasFromXML() end
function Enterable.loadCharacterTargetNodeModifier() end
function Enterable.loadDashboardGroupFromXML() end
function Enterable.mountDynamic() end
function Enterable.onDelete() end
function Enterable.onLoad() end
function Enterable.onPostUpdate() end
function Enterable.onPreLoad() end
function Enterable.onReadStream() end
function Enterable.onRegisterActionEvents() end
function Enterable.onSetBroken() end
function Enterable.onUpdate() end
function Enterable.onWriteStream() end
function Enterable.prerequisitesPresent() end
function Enterable.registerEventListeners() end
function Enterable.registerEvents() end
function Enterable.registerFunctions() end
function Enterable.registerOverwrittenFunctions() end
function Enterable.removeToolCameras() end
function Enterable.restoreVehicleCharacter() end
function Enterable.saveStatsToXMLFile() end
function Enterable.setActiveCameraIndex() end
function Enterable.setIsTabbable() end
function Enterable.setMirrorVisible() end
function Enterable.setRandomVehicleCharacter() end
function Enterable.setVehicleCharacter() end
function Enterable.updateCharacterTargetNodeModifier() end
