---@class EventIds
EventIds = {
    EVENT_ADD_MONEY = 137,
    EVENT_AIVEHICLE_IS_BLOCKED = 81,
    EVENT_AIVEHICLE_SET_CONVEYORBELT_ANGLE = 82,
    EVENT_AIVEHICLE_SET_STARTED = 80,
    EVENT_ANIMAL_ADD = 147,
    EVENT_ANIMAL_CLEAN = 150,
    EVENT_ANIMAL_DEALER = 152,
    EVENT_ANIMAL_FARM_TRAILER = 153,
    EVENT_ANIMAL_HUSBANDRY_NO_MORE_PALLET_SPACE = 146,
    EVENT_ANIMAL_HUSBANDRY_PICKUP_OBJECT = 145,
    EVENT_ANIMAL_LOADING_TRIGGER_EVENT = 115,
    EVENT_ANIMAL_NAME = 151,
    EVENT_ANIMAL_REMOVE = 148,
    EVENT_ANIMAL_RIDING = 149,
    EVENT_ANIMATED_OBJECT = 105,
    EVENT_ANIMATED_VEHICLE_START = 66,
    EVENT_ANIMATED_VEHICLE_STOP = 67,
    EVENT_BALECREATE = 79,
    EVENT_BALER_AREA = 83,
    EVENT_BALER_CREATE_BALE = 84,
    EVENT_BALER_DELETE_BALE = 85,
    EVENT_BALER_SET_BALE_TIME = 86,
    EVENT_BALER_SET_IS_UNLOADING_BALE = 118,
    EVENT_BALE_LOADER_STATE = 106,
    EVENT_BALE_WRAPPER_STATE = 107,
    EVENT_BRAND_SALE = 131,
    EVENT_BUNKER_SILO_CLOSE = 126,
    EVENT_BUNKER_SILO_OPEN = 127,
    EVENT_BUY_HANDTOOL = 49,
    EVENT_BUY_OBJECT = 48,
    EVENT_BUY_PLACEABLE = 47,
    EVENT_BUY_VEHICLE = 46,
    EVENT_CHAINSAW_CUT = 159,
    EVENT_CHAINSAW_DELIMB = 160,
    EVENT_CHAINSAW_STATE = 158,
    EVENT_CHANGE_LOAN = 136,
    EVENT_CHANGE_VEHICLE_CONFIG = 53,
    EVENT_CHAT = 3,
    EVENT_CHEAT_MONEY = 184,
    EVENT_CLIENT_START_MISSION = 31,
    EVENT_COMBINE_AREA = 87,
    EVENT_COMBINE_ENABLE_STRAW = 89,
    EVENT_CONNECTION_REQUEST = 5,
    EVENT_CONNECTION_REQUEST_ANSWER = 4,
    EVENT_CONTRACTING_STATE = 190,
    EVENT_CRUISECONTROL_SET_SPEED = 63,
    EVENT_CRUISECONTROL_SET_STATE = 62,
    EVENT_CULTIVATOR_AREA = 92,
    EVENT_CUTTER_AREA = 93,
    EVENT_CYLINDERED_EASY_CONTROL_CHANGE = 90,
    EVENT_DOG_FEED = 155,
    EVENT_DOG_FETCH_ITEM = 157,
    EVENT_DOG_FOLLOW = 156,
    EVENT_DOG_PET = 154,
    EVENT_ENVIRONMENT_PRICE = 7,
    EVENT_ENVIRONMENT_TIME = 8,
    EVENT_FARMLAND_INITIAL_STATE = 140,
    EVENT_FARMLAND_STATE = 139,
    EVENT_FARM_CREATE_UPDATE = 186,
    EVENT_FARM_DESTROY = 187,
    EVENT_FARM_INITIAL_STATE = 188,
    EVENT_FERTILIZER_TRAILER_SET_IS_FILLING = 121,
    EVENT_FILLUNIT_UNLOAD = 77,
    EVENT_FINANCE_STATS = 138,
    EVENT_FINISHED_LOADING = 1,
    EVENT_FOG_STATE_EVENT = 11,
    EVENT_FOLDABLE_SET_FOLD_DIRECTION = 68,
    EVENT_FORAGE_WAGON_AREA = 94,
    EVENT_FRUIT_PREPARER_AREA = 104,
    EVENT_FUEL_TRAILER_SET_IS_FILLING = 120,
    EVENT_GAME_PAUSE = 26,
    EVENT_GET_ADMIN = 174,
    EVENT_GET_ADMIN_ANSWER = 175,
    EVENT_GET_BANS = 196,
    EVENT_GREAT_DEMANDS = 132,
    EVENT_GREAT_DEMAND_START_MESSAGE = 133,
    EVENT_GREENHOUSE_SET_WATER_TANK_FILLING = 141,
    EVENT_GROWTH_UPDATE = 23,
    EVENT_HIGHPRESSURE_WASHER_LANCE_STATE = 144,
    EVENT_HIGHPRESSURE_WASHER_STATE = 143,
    EVENT_HIGHPRESSURE_WASHER_TURN_ON = 142,
    EVENT_HONK = 72,
    EVENT_INGAME_MISSION_INTERVAL = 183,
    EVENT_INGAME_MISSION_SERVER = 180,
    EVENT_INGAME_MISSION_SERVER_ANSWER = 181,
    EVENT_JUMP = 73,
    EVENT_KICK_BAN = 177,
    EVENT_KICK_BAN_NOTIFICATION = 178,
    EVENT_LANDSCAPING_PAINT = 195,
    EVENT_LANDSCAPING_SCULPT = 194,
    EVENT_LOADTRIGGER_SET_IS_LOADING = 168,
    EVENT_MASTER_USER_LOGIN = 179,
    EVENT_MESH = 29,
    EVENT_MILKROBOT_CHANGED_STATE = 122,
    EVENT_MISSION_CANCEL = 171,
    EVENT_MISSION_DISMISS = 173,
    EVENT_MISSION_FINISHED = 172,
    EVENT_MISSION_INFO_DYNAMIC = 176,
    EVENT_MISSION_START = 169,
    EVENT_MISSION_STARTED = 170,
    EVENT_MIXERWAGON_BALE_NOT_ACCEPTED = 129,
    EVENT_MONEY = 32,
    EVENT_MONEY_CHANGE = 192,
    EVENT_MOWER_AREA = 95,
    EVENT_MOWER_TOGGLE_WINDROW_DROP = 109,
    EVENT_OBJECT_OWNER_CHANGE = 185,
    EVENT_ON_CREATE_LOADED_OBJECT = 25,
    EVENT_PLANE_MOVER = 111,
    EVENT_PLANT_LIMIT_TO_FIELD = 99,
    EVENT_PLAYER_PERMISSIONS = 30,
    EVENT_PLAYER_PICKUP_OBJECT = 16,
    EVENT_PLAYER_SET_FARM = 14,
    EVENT_PLAYER_SET_FARM_ANSWER = 15,
    EVENT_PLAYER_SET_HANDTOOL = 13,
    EVENT_PLAYER_SWITCHED_FARM = 19,
    EVENT_PLAYER_TELEPORT = 12,
    EVENT_PLAYER_THROW_OBJECT = 17,
    EVENT_PLAYER_TOGGLE_LIGHT = 18,
    EVENT_PLOW_AREA = 96,
    EVENT_PLOW_LIMIT_TO_FIELD = 98,
    EVENT_PLOW_ROTATION = 97,
    EVENT_READY_EVENT = 2,
    EVENT_RECEIVINGHOPPER_SET_CREATE_BOXES = 74,
    EVENT_REMOVE_GROUND_VALUE_AREA = 135,
    EVENT_REMOVE_PLAYER_FROM_FARM = 191,
    EVENT_REQUEST_MONEY_CHANGE = 193,
    EVENT_RESET_VEHICLE = 52,
    EVENT_REVERSE_DRIVING_SET_STATE = 112,
    EVENT_RIDGE_MARKER_SET_STATE = 108,
    EVENT_SALES = 130,
    EVENT_SAVE = 182,
    EVENT_SAVEGAME_SETTTINGS = 6,
    EVENT_SELL_HANDTOOL = 50,
    EVENT_SELL_PLACEABLE = 51,
    EVENT_SELL_SPECIFIC_VEHICLE = 45,
    EVENT_SELL_VEHICLE = 44,
    EVENT_SELL_WOOD = 37,
    EVENT_SEND_LOCOMOTIVE_TO_SPLINE_POSITION = 167,
    EVENT_SEND_MONEY = 43,
    EVENT_SET_COVER_STATE = 110,
    EVENT_SET_CRABSTEERING = 114,
    EVENT_SET_DENSITY_MAP = 20,
    EVENT_SET_DISCHARGE_STATE = 91,
    EVENT_SET_FILLUNIT_IS_FILLING = 65,
    EVENT_SET_MOTOR_TURNED_ON = 64,
    EVENT_SET_PICKUP_STATE = 70,
    EVENT_SET_PIPE_STATE = 88,
    EVENT_SET_SPLIT_SHAPES = 21,
    EVENT_SET_TURNED_ON = 69,
    EVENT_SET_WORK_MODE = 113,
    EVENT_SHUTDOWN = 24,
    EVENT_SILO_TRIGGER_SET_IS_FILLING = 128,
    EVENT_SLEEP_REQUEST = 35,
    EVENT_SLEEP_RESPONSE = 36,
    EVENT_SLEEP_START = 33,
    EVENT_SLEEP_STOP = 34,
    EVENT_SOWING_MACHINE_AREA = 100,
    EVENT_SOWING_MACHINE_SET_SEED_INDEX = 123,
    EVENT_SPRAYER_AREA = 101,
    EVENT_SPRAYER_SET_IS_FILLING = 116,
    EVENT_STARTLE_ANIMAL = 117,
    EVENT_STRAW_BLOWER_DOOR_OPEN = 125,
    EVENT_TEDDER_AREA = 102,
    EVENT_TENSION_BELT = 75,
    EVENT_TENSION_BELT_REFRESH = 76,
    EVENT_TRAILER_TIP_AREA = 134,
    EVENT_TRAILER_TOGGLE_TIP_SIDE = 71,
    EVENT_TRAIN_START = 78,
    EVENT_TRANSFER_MONEY = 189,
    EVENT_TREE_GROW = 166,
    EVENT_TREE_PLANT = 165,
    EVENT_TREE_PLANTER_LOAD_PALLET = 124,
    EVENT_UNBAN = 197,
    EVENT_UPDATE_SPLIT_SHAPES = 22,
    EVENT_USER = 27,
    EVENT_USER_DATA = 28,
    EVENT_VEHICLE_ATTACH = 54,
    EVENT_VEHICLE_BROKEN = 42,
    EVENT_VEHICLE_BUNDLE_ATTACH = 55,
    EVENT_VEHICLE_DETACH = 56,
    EVENT_VEHICLE_ENTER_REQUEST = 39,
    EVENT_VEHICLE_ENTER_RESPONSE = 40,
    EVENT_VEHICLE_LEAVE = 41,
    EVENT_VEHICLE_LOWER_ALL_IMPLEMENT = 58,
    EVENT_VEHICLE_LOWER_IMPLEMENT = 57,
    EVENT_VEHICLE_REMOVE = 38,
    EVENT_VEHICLE_SET_BEACON_LIGHT = 59,
    EVENT_VEHICLE_SET_LIGHT = 61,
    EVENT_VEHICLE_SET_TURNLIGHT = 60,
    EVENT_WATER_TRAILER_SET_IS_FILLING = 119,
    EVENT_WEARABLE_REPAIR = 161,
    EVENT_WEATHER_ADD_OBJECT = 9,
    EVENT_WINDROW_AREA = 103,
    EVENT_WIND_OBJECT_CHANGED_EVENT = 10,
    EVENT_WOODHARVESTER_CUT_TREE = 162,
    EVENT_WOODHARVESTER_ON_CUT_TREE = 163,
    EVENT_WOODHARVESTER_ON_DELIMB_TREE = 164,
    MAX_EVENT_ID = 65535,
    SEND_NUM_BITS = 16,
    eventClasses = {
    },
    eventIdNext = 198,
    eventIdToClass = {
        [1] = {
            eventId = 1,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [138] = {
            eventId = 138,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [139] = {
            eventId = 139,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [140] = {
            eventId = 140,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [136] = {
            eventId = 136,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [129] = {
            eventId = 129,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [132] = {
            eventId = 132,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [127] = {
            eventId = 127,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [126] = {
            eventId = 126,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [141] = {
            eventId = 141,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [144] = {
            eventId = 144,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [150] = {
            eventId = 150,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [151] = {
            eventId = 151,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [142] = {
            eventId = 142,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [149] = {
            eventId = 149,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [147] = {
            eventId = 147,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [148] = {
            eventId = 148,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [146] = {
            eventId = 146,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [152] = {
            eventId = 152,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            runLocal = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [124] = {
            eventId = 124,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [119] = {
            eventId = 119,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [99] = {
            eventId = 99,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [105] = {
            eventId = 105,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [106] = {
            eventId = 106,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [98] = {
            eventId = 98,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [91] = {
            eventId = 91,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [97] = {
            eventId = 97,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [90] = {
            eventId = 90,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [123] = {
            eventId = 123,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [107] = {
            eventId = 107,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [109] = {
            eventId = 109,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [114] = {
            eventId = 114,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [118] = {
            eventId = 118,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [108] = {
            eventId = 108,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [113] = {
            eventId = 113,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [110] = {
            eventId = 110,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [112] = {
            eventId = 112,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [89] = {
            eventId = 89,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [153] = {
            eventId = 153,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            runLocal = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [155] = {
            eventId = 155,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [182] = {
            eventId = 182,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [184] = {
            eventId = 184,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [185] = {
            eventId = 185,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [178] = {
            eventId = 178,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [176] = {
            eventId = 176,
            sendCapNumBits = 4,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [177] = {
            eventId = 177,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [175] = {
            ACCESS_DENIED = 1,
            ACCESS_GRANTED = 0,
            NOT_SUPPORTED = 2,
            eventId = 175,
            sendNumBits = 2,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            onAnswerOk = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [174] = {
            eventId = 174,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [186] = {
            eventId = 186,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [188] = {
            eventId = 188,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [193] = {
            eventId = 193,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [194] = {
            eventId = 194,

            class = function () end,
            copy = function () end,
            delete = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            onSculptingFinished = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [187] = {
            eventId = 187,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [192] = {
            eventId = 192,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [190] = {
            eventId = 190,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [191] = {
            eventId = 191,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [189] = {
            eventId = 189,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [154] = {
            eventId = 154,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [173] = {
            eventId = 173,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [171] = {
            eventId = 171,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [160] = {
            eventId = 160,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [161] = {
            eventId = 161,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [162] = {
            eventId = 162,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [159] = {
            eventId = 159,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [157] = {
            eventId = 157,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [158] = {
            eventId = 158,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [156] = {
            eventId = 156,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [172] = {
            eventId = 172,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [163] = {
            eventId = 163,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [165] = {
            eventId = 165,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [169] = {
            eventId = 169,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [170] = {
            eventId = 170,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [164] = {
            eventId = 164,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [168] = {
            eventId = 168,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [166] = {
            eventId = 166,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [167] = {
            eventId = 167,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [196] = {
            eventId = 196,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [88] = {
            eventId = 88,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [84] = {
            eventId = 84,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [27] = {
            SEND_NUM_BITS = 5,
            eventId = 27,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [28] = {
            SEND_NUM_BITS = 5,
            eventId = 28,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [29] = {
            eventId = 29,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [26] = {
            eventId = 26,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [24] = {
            eventId = 24,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [25] = {
            eventId = 25,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [22] = {
            eventId = 22,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [21] = {
            PartSizeBits = 160000,
            eventId = 21,

            class = function () end,
            copy = function () end,
            delete = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newAck = function () end,
            newReceiving = function () end,
            processReadData = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [30] = {
            eventId = 30,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [33] = {
            eventId = 33,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [38] = {
            eventId = 38,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [39] = {
            eventId = 39,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [31] = {
            eventId = 31,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [37] = {
            eventId = 37,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [35] = {
            eventId = 35,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [36] = {
            eventId = 36,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [34] = {
            eventId = 34,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [40] = {
            eventId = 40,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [20] = {
            PartSizeBits = 160000,
            eventId = 20,

            class = function () end,
            copy = function () end,
            delete = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newAck = function () end,
            newReceiving = function () end,
            processReadData = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [18] = {
            eventId = 18,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [6] = {
            eventId = 6,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [8] = {
            eventId = 8,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [9] = {
            eventId = 9,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [5] = {
            eventId = 5,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [3] = {
            eventId = 3,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [4] = {
            ALREADY_IN_USE = 5,
            ANSWER_ALWAYS_DENIED = 4,
            ANSWER_DENIED = 1,
            ANSWER_FULL = 3,
            ANSWER_OK = 0,
            ANSWER_WRONG_PASSWORD = 2,
            eventId = 4,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [2] = {
            eventId = 2,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [19] = {
            NO_FARM = 126,
            eventId = 19,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [10] = {
            eventId = 10,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [12] = {
            eventId = 12,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newExitVehicle = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [16] = {
            eventId = 16,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [17] = {
            eventId = 17,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [11] = {
            SEND_BITS_FOG_DURATION = 4,
            SEND_BITS_FOG_FACTOR = 3,
            SEND_BITS_FOG_STATE = 6,
            eventId = 11,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [15] = {
            SEND_NUM_BITS = 2,
            STATE = {
                OK = 1,
                PASSWORD_REQUIRED = 2,
            },
            eventId = 15,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [13] = {
            eventId = 13,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [14] = {
            eventId = 14,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [86] = {
            eventId = 86,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [41] = {
            eventId = 41,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [44] = {
            SELL_NO_PERMISSION = 2,
            SELL_SUCCESS = 0,
            SELL_VEHICLE_IN_USE = 1,
            eventId = 44,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [70] = {
            eventId = 70,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [71] = {
            eventId = 71,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [72] = {
            eventId = 72,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [69] = {
            eventId = 69,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [67] = {
            eventId = 67,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [68] = {
            eventId = 68,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [66] = {
            eventId = 66,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [65] = {
            eventId = 65,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [73] = {
            eventId = 73,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [75] = {
            eventId = 75,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [81] = {
            eventId = 81,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [82] = {
            eventId = 82,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [74] = {
            eventId = 74,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [80] = {
            eventId = 80,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [76] = {
            eventId = 76,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [77] = {
            eventId = 77,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [42] = {
            eventId = 42,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [64] = {
            eventId = 64,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [62] = {
            eventId = 62,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [50] = {
            STATE_FAILED = 1,
            STATE_IN_USE = 3,
            STATE_NO_PERMISSION = 2,
            STATE_SUCCESS = 0,
            eventId = 50,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            readStream = function () end,
            removeHandTool = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [51] = {
            STATE_FAILED = 1,
            STATE_IN_USE = 3,
            STATE_NO_PERMISSION = 2,
            STATE_SUCCESS = 0,
            eventId = 51,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [52] = {
            STATE_FAILED = 1,
            STATE_IN_USE = 3,
            STATE_NO_PERMISSION = 2,
            STATE_SUCCESS = 0,
            eventId = 52,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [49] = {
            STATE_FAILED_TO_LOAD = 2,
            STATE_NOT_ENOUGH_MONEY = 3,
            STATE_NO_PERMISSION = 1,
            STATE_SUCCESS = 0,
            eventId = 49,

            addHandTool = function () end,
            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [47] = {
            STATE_FAILED_TO_LOAD = 1,
            STATE_NOT_ENOUGH_MONEY = 4,
            STATE_NO_PERMISSION = 3,
            STATE_NO_SPACE = 2,
            STATE_SUCCESS = 0,
            STATE_TERRAIN_DEFORMATION_FAILED = 5,
            eventId = 47,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [48] = {
            STATE_FAILED_TO_LOAD = 1,
            STATE_LIMIT_REACHED = 3,
            STATE_NOT_ENOUGH_MONEY = 4,
            STATE_NO_SPACE = 2,
            STATE_SUCCESS = 0,
            eventId = 48,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [46] = {
            STATE_FAILED_TO_LOAD = 1,
            STATE_NOT_ENOUGH_MONEY = 4,
            STATE_NO_PERMISSION = 3,
            STATE_NO_SPACE = 2,
            STATE_SUCCESS = 0,
            eventId = 46,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            onVehicleBoughtCallback = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [63] = {
            eventId = 63,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [53] = {
            eventId = 53,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            newServerToClient = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [55] = {
            eventId = 55,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [60] = {
            eventId = 60,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [61] = {
            eventId = 61,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [54] = {
            eventId = 54,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [59] = {
            eventId = 59,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [56] = {
            eventId = 56,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [57] = {
            eventId = 57,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            sendEvent = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
        [197] = {
            eventId = 197,

            class = function () end,
            copy = function () end,
            emptyNew = function () end,
            isa = function () end,
            new = function () end,
            readStream = function () end,
            run = function () end,
            superClass = function () end,
            writeStream = function () end,
        },
    },
    eventIdsUsed = {
        [1] = true,
        [138] = true,
        [139] = true,
        [140] = true,
        [136] = true,
        [129] = true,
        [132] = true,
        [127] = true,
        [126] = true,
        [141] = true,
        [144] = true,
        [150] = true,
        [151] = true,
        [142] = true,
        [149] = true,
        [147] = true,
        [148] = true,
        [146] = true,
        [152] = true,
        [124] = true,
        [119] = true,
        [99] = true,
        [105] = true,
        [106] = true,
        [98] = true,
        [91] = true,
        [97] = true,
        [90] = true,
        [123] = true,
        [107] = true,
        [109] = true,
        [114] = true,
        [118] = true,
        [108] = true,
        [113] = true,
        [110] = true,
        [112] = true,
        [89] = true,
        [153] = true,
        [155] = true,
        [182] = true,
        [184] = true,
        [185] = true,
        [178] = true,
        [176] = true,
        [177] = true,
        [175] = true,
        [174] = true,
        [186] = true,
        [188] = true,
        [193] = true,
        [194] = true,
        [187] = true,
        [192] = true,
        [190] = true,
        [191] = true,
        [189] = true,
        [154] = true,
        [173] = true,
        [171] = true,
        [160] = true,
        [161] = true,
        [162] = true,
        [159] = true,
        [157] = true,
        [158] = true,
        [156] = true,
        [172] = true,
        [163] = true,
        [165] = true,
        [169] = true,
        [170] = true,
        [164] = true,
        [168] = true,
        [166] = true,
        [167] = true,
        [196] = true,
        [88] = true,
        [84] = true,
        [27] = true,
        [28] = true,
        [29] = true,
        [26] = true,
        [24] = true,
        [25] = true,
        [22] = true,
        [21] = true,
        [30] = true,
        [33] = true,
        [38] = true,
        [39] = true,
        [31] = true,
        [37] = true,
        [35] = true,
        [36] = true,
        [34] = true,
        [40] = true,
        [20] = true,
        [18] = true,
        [6] = true,
        [8] = true,
        [9] = true,
        [5] = true,
        [3] = true,
        [4] = true,
        [2] = true,
        [19] = true,
        [10] = true,
        [12] = true,
        [16] = true,
        [17] = true,
        [11] = true,
        [15] = true,
        [13] = true,
        [14] = true,
        [86] = true,
        [41] = true,
        [44] = true,
        [70] = true,
        [71] = true,
        [72] = true,
        [69] = true,
        [67] = true,
        [68] = true,
        [66] = true,
        [65] = true,
        [73] = true,
        [75] = true,
        [81] = true,
        [82] = true,
        [74] = true,
        [80] = true,
        [76] = true,
        [77] = true,
        [42] = true,
        [64] = true,
        [62] = true,
        [50] = true,
        [51] = true,
        [52] = true,
        [49] = true,
        [47] = true,
        [48] = true,
        [46] = true,
        [63] = true,
        [53] = true,
        [55] = true,
        [60] = true,
        [61] = true,
        [54] = true,
        [59] = true,
        [56] = true,
        [57] = true,
        [197] = true,
    },
}

function EventIds.assignEventId() end
function EventIds.assignEventIds() end
function EventIds.assignEventObjectId() end
function EventIds.getEventClassById() end
function EventIds.getEventClassByName() end
