---@class FarmManager
FarmManager = {
    FARM_ID_SEND_NUM_BITS = 4,
    INVALID_FARM_ID = 15,
    MAX_FARM_ID = 8,
    MAX_NUM_FARMS = 8,
    SINGLEPLAYER_FARM_ID = 1,
    SINGLEPLAYER_UUID = 'player',
    SPECTATOR_FARM_ID = 0,
}

function FarmManager.appendFarm() end
function FarmManager.class() end
function FarmManager.consoleCommandCreateFarm() end
function FarmManager.consoleCommandSetFarm() end
function FarmManager.copy() end
function FarmManager.createFarm() end
function FarmManager.delete() end
function FarmManager.destroyFarm() end
function FarmManager.findNextFarmId() end
function FarmManager.getFarmById() end
function FarmManager.getFarmByUserId() end
function FarmManager.getFarmForUniqueUserId() end
function FarmManager.getFarms() end
function FarmManager.getSleepCamera() end
function FarmManager.getSpawnPoint() end
function FarmManager.initDataStructures() end
function FarmManager.isa() end
function FarmManager.loadDefaults() end
function FarmManager.loadFromXMLFile() end
function FarmManager.loadMapData() end
function FarmManager.mergeFarmlandsForSingleplayer() end
function FarmManager.mergeFarmsForSingleplayer() end
function FarmManager.mergeObjectsForSingleplayer() end
function FarmManager.new() end
function FarmManager.onFarmObjectCreated() end
function FarmManager.onFarmObjectDeleted() end
function FarmManager.playerJoinedGame() end
function FarmManager.playerQuitGame() end
function FarmManager.removeFarm() end
function FarmManager.removeUserFromFarm() end
function FarmManager.saveToXMLFile() end
function FarmManager.superClass() end
function FarmManager.transferMoney() end
function FarmManager.unloadMapData() end
function FarmManager.update() end
function FarmManager.updateFarmStats() end
function FarmManager.updateFarms() end
