---@class FinanceStats
FinanceStats = {
    filledI18N = false,
    statNameToIndex = {
        animalUpkeep = 11,
        constructionCost = 5,
        fieldPurchase = 7,
        fieldSelling = 8,
        harvestIncome = 23,
        incomeBga = 24,
        loanInterest = 28,
        missionIncome = 25,
        newAnimalsCost = 3,
        newVehiclesCost = 1,
        other = 27,
        propertyIncome = 13,
        propertyMaintenance = 12,
        purchaseFertilizer = 20,
        purchaseFuel = 18,
        purchaseSaplings = 21,
        purchaseSeeds = 19,
        purchaseWater = 22,
        soldAnimals = 4,
        soldBales = 15,
        soldBuildings = 6,
        soldMilk = 17,
        soldVehicles = 2,
        soldWood = 14,
        soldWool = 16,
        vehicleLeasingCost = 10,
        vehicleRunningCost = 9,
        wagePayment = 26,
    },
    statNames = {
        [1] = 'newVehiclesCost',
        [19] = 'purchaseSeeds',
        [20] = 'purchaseFertilizer',
        [18] = 'purchaseFuel',
        [16] = 'soldWool',
        [17] = 'soldMilk',
        [15] = 'soldBales',
        [21] = 'purchaseSaplings',
        [23] = 'harvestIncome',
        [26] = 'wagePayment',
        [22] = 'purchaseWater',
        [25] = 'missionIncome',
        [24] = 'incomeBga',
        [27] = 'other',
        [14] = 'soldWood',
        [12] = 'propertyMaintenance',
        [4] = 'soldAnimals',
        [5] = 'constructionCost',
        [3] = 'newAnimalsCost',
        [2] = 'soldVehicles',
        [13] = 'propertyIncome',
        [6] = 'soldBuildings',
        [8] = 'fieldSelling',
        [11] = 'animalUpkeep',
        [7] = 'fieldPurchase',
        [10] = 'vehicleLeasingCost',
        [9] = 'vehicleRunningCost',
        [28] = 'loanInterest',
    },
    statNamesI18n = {
        animalUpkeep = 'Animal Upkeep',
        constructionCost = 'Construction Cost',
        fieldPurchase = 'Land purchase',
        fieldSelling = 'Sold land',
        harvestIncome = 'Harvest Income',
        incomeBga = 'Biogas Plant Income',
        loanInterest = 'Loan Interest',
        missionIncome = 'Contracts Income',
        newAnimalsCost = 'New Livestock',
        newVehiclesCost = 'New Vehicles',
        other = 'Other',
        propertyIncome = 'Property Income',
        propertyMaintenance = 'Property Maintenance',
        purchaseFertilizer = 'Fertilizer Costs',
        purchaseFuel = 'Fuel Costs',
        purchaseSaplings = 'Saplings Costs',
        purchaseSeeds = 'Seed Costs',
        purchaseWater = 'Water Costs',
        soldAnimals = 'Sold Animals',
        soldBales = 'Sold Bales',
        soldBuildings = 'Sold Buildings',
        soldMilk = 'Sold Milk',
        soldVehicles = 'Sold Vehicles',
        soldWood = 'Sold Wood',
        soldWool = 'Sold Wool',
        vehicleLeasingCost = 'Vehicle Leasing Costs',
        vehicleRunningCost = 'Vehicle Running Costs',
        wagePayment = 'Wage Payment',
    },
}

function FinanceStats.class() end
function FinanceStats.copy() end
function FinanceStats.isa() end
function FinanceStats.loadFromXMLFile() end
function FinanceStats.merge() end
function FinanceStats.new() end
function FinanceStats.saveToXMLFile() end
function FinanceStats.superClass() end
