---@class Foldable
Foldable = {} -- empty

function Foldable.actionEventFold() end
function Foldable.actionEventFoldMiddle() end
function Foldable.allowLoadMovingToolStates() end
function Foldable.getAllowDynamicMountObjects() end
function Foldable.getAllowsLowering() end
function Foldable.getCanAIImplementContinueWork() end
function Foldable.getCanBeSelected() end
function Foldable.getCanBeTurnedOn() end
function Foldable.getCompensationAngleScale() end
function Foldable.getFoldAnimTime() end
function Foldable.getIsAdditionalCharacterActive() end
function Foldable.getIsFoldAllowed() end
function Foldable.getIsFoldMiddleAllowed() end
function Foldable.getIsGroundAdjustedNodeActive() end
function Foldable.getIsInWorkPosition() end
function Foldable.getIsInputAttacherActive() end
function Foldable.getIsLevelerPickupNodeActive() end
function Foldable.getIsLowered() end
function Foldable.getIsMovingToolActive() end
function Foldable.getIsNextCoverStateAllowed() end
function Foldable.getIsSpeedRotatingPartActive() end
function Foldable.getIsSprayTypeActive() end
function Foldable.getIsUnfolded() end
function Foldable.getIsVersatileYRotActive() end
function Foldable.getIsWorkAreaActive() end
function Foldable.getSpecValueWorkingWidth() end
function Foldable.getToggledFoldDirection() end
function Foldable.getToggledFoldMiddleDirection() end
function Foldable.getTurnedOnNotAllowedWarning() end
function Foldable.initSpecialization() end
function Foldable.isDetachAllowed() end
function Foldable.loadAdditionalCharacterFromXML() end
function Foldable.loadCompensationNodeFromXML() end
function Foldable.loadDynamicWheelDataFromXML() end
function Foldable.loadGroundAdjustedNodeFromXML() end
function Foldable.loadInputAttacherJoint() end
function Foldable.loadLevelerNodeFromXML() end
function Foldable.loadMovingToolFromXML() end
function Foldable.loadSpecValueWorkingWidth() end
function Foldable.loadSpeedRotatingPartFromXML() end
function Foldable.loadSprayTypeFromXML() end
function Foldable.loadWorkAreaFromXML() end
function Foldable.onAIImplementEnd() end
function Foldable.onAIImplementEndLine() end
function Foldable.onAIImplementStart() end
function Foldable.onAIImplementStartLine() end
function Foldable.onDeactivate() end
function Foldable.onLoad() end
function Foldable.onPostLoad() end
function Foldable.onReadStream() end
function Foldable.onRegisterActionEvents() end
function Foldable.onSetLoweredAll() end
function Foldable.onUpdate() end
function Foldable.onWriteStream() end
function Foldable.prerequisitesPresent() end
function Foldable.registerEventListeners() end
function Foldable.registerEvents() end
function Foldable.registerFunctions() end
function Foldable.registerLoweringActionEvent() end
function Foldable.registerOverwrittenFunctions() end
function Foldable.registerSelfLoweringActionEvent() end
function Foldable.saveToXMLFile() end
function Foldable.setAnimTime() end
function Foldable.setFoldDirection() end
function Foldable.setFoldState() end
function Foldable.updateActionEventFold() end
function Foldable.updateActionEventFoldMiddle() end
