---@class InGameMenuGeneralSettingsFrame
InGameMenuGeneralSettingsFrame = {
    CONTROLS = {
        BOX_LAYOUT = 'boxLayout',
        BUTTON_NATIVE_HELP = 'buttonNativeHelp',
        CHECKBOX_AUTO_HELP = 'checkAutoHelp',
        CHECKBOX_COLORBLIND_MODE = 'checkColorBlindMode',
        CHECKBOX_HELP_ICONS = 'checkHelpIcons',
        CHECKBOX_INVERT_Y_LOOK = 'checkInvertYLook',
        CHECKBOX_IS_RADIO_ACTIVE = 'checkIsRadioActive',
        CHECKBOX_IS_RADIO_VEHICLE_ONLY = 'checkIsRadioVehicleOnly',
        CHECKBOX_IS_TRAIN_TABBABLE = 'checkIsTrainTabbable',
        CHECKBOX_RESET_CAMERA = 'checkResetCamera',
        CHECKBOX_SHOW_FIELD_INFO = 'checkShowFieldInfo',
        CHECKBOX_SHOW_TRIGGER_MARKER = 'checkShowTriggerMarker',
        CHECKBOX_USE_ACRE = 'checkUseAcre',
        CHECKBOX_USE_EASY_ARM_CONTROLER = 'checkUseEasyArmControl',
        CHECKBOX_USE_MILES = 'checkUseMiles',
        CHECKBOX_USE_WORLD_CAMERA = 'checkUseWorldCamera',
        HELP_BOX = 'generalSettingsHelpBox',
        HELP_BOX_TEXT = 'generalSettingsHelpBoxText',
        OPTION_CAMERA_SENSITIVITY = 'multiCameraSensitivity',
        OPTION_INPUT_HELP_MODE = 'multiInputHelpMode',
        OPTION_MONEY_UNIT = 'multiMoneyUnit',
        OPTION_STEERING_BACK_SPEED = 'multiSteeringBackSpeed',
        OPTION_VEHICLE_ARM_SENSITIVITY = 'multiVehicleArmSensitivity',
        OPTION_VOLUME_ENVIRONMENT = 'multiEnvironmentVolume',
        OPTION_VOLUME_GUI = 'multiVolumeGUI',
        OPTION_VOLUME_MASTER = 'multiMasterVolume',
        OPTION_VOLUME_RADIO = 'multiRadioVolume',
        OPTION_VOLUME_VEHICLE = 'multiVehicleVolume',
        SETTINGS_CONTAINER = 'settingsContainer',
    },
}

function InGameMenuGeneralSettingsFrame.class() end
function InGameMenuGeneralSettingsFrame.copy() end
function InGameMenuGeneralSettingsFrame.copyAttributes() end
function InGameMenuGeneralSettingsFrame.getMainElementPosition() end
function InGameMenuGeneralSettingsFrame.getMainElementSize() end
function InGameMenuGeneralSettingsFrame.initialize() end
function InGameMenuGeneralSettingsFrame.isa() end
function InGameMenuGeneralSettingsFrame.new() end
function InGameMenuGeneralSettingsFrame.onClickCheckbox() end
function InGameMenuGeneralSettingsFrame.onClickMultiOption() end
function InGameMenuGeneralSettingsFrame.onClickNativeHelp() end
function InGameMenuGeneralSettingsFrame.onFrameClose() end
function InGameMenuGeneralSettingsFrame.onFrameOpen() end
function InGameMenuGeneralSettingsFrame.onToolTipBoxTextChanged() end
function InGameMenuGeneralSettingsFrame.superClass() end
function InGameMenuGeneralSettingsFrame.updateGeneralSettings() end
function InGameMenuGeneralSettingsFrame.updateToolTipBoxVisibility() end
