---@class InputHelpElement
InputHelpElement = {
    AXIS_ICON = {
        BEET_PICKUP_TRANS_X = 'BEET_PICKUP_TRANS_X',
        BEET_PICKUP_TRANS_Y = 'BEET_PICKUP_TRANS_Y',
        CRANE_ARM1_ROTATE_X = 'CRANE_ARM1_ROTATE_X',
        CRANE_ARM1_ROTATE_Y = 'CRANE_ARM1_ROTATE_Y',
        CRANE_ARM1_TRANSLATE = 'CRANE_ARM1_TRANSLATE',
        CRANE_ARM2_ROTATE_TOOL = 'CRANE_ARM2_ROTATE_TOOL',
        CRANE_ARM2_ROTATE_X = 'CRANE_ARM2_ROTATE_X',
        CRANE_ARM2_TRANSLATE = 'CRANE_ARM2_TRANSLATE',
        CRANE_EC_TRANSLATE_Y = 'CRANE_EC_TRANSLATE_Y',
        CRANE_EC_TRANSLATE_Z = 'CRANE_EC_TRANSLATE_Z',
        DRAWBAR_ROTATE_X = 'DRAWBAR_ROTATE_X',
        FRONTLOADER_ARM_ROTATE = 'FRONTLOADER_ARM_ROTATE',
        FRONTLOADER_ARM_ROTATE_TOOL = 'FRONTLOADER_ARM_ROTATE_TOOL',
        GRABBER_OPEN_CLOSE = 'GRABBER_OPEN_CLOSE',
        GRABBER_ROTATE_Y = 'GRABBER_ROTATE_Y',
        IMPLEMENT_ATTACHER_ROTX = 'IMPLEMENT_ATTACHER_ROTX',
        IMPLEMENT_ATTACHER_TRANS = 'IMPLEMENT_ATTACHER_TRANS',
        PIPE_END_ROTATE = 'PIPE_END_ROTATE',
        PIPE_ROTATE_Y = 'PIPE_ROTATE_Y',
        REEL_TRANSLATE_X = 'REEL_TRANSLATE_X',
        REEL_TRANSLATE_Y = 'REEL_TRANSLATE_Y',
        SEAT_ROT_Y = 'SEAT_ROT_Y',
        SPRAYER_ARM_TRANSLATE_Y = 'SPRAYER_ARM_TRANSLATE_Y',
        SUPPORT_ARM_TRANSLATE_Y = 'SUPPORT_ARM_TRANSLATE_Y',
        TOOL_OPEN_CLOSE = 'TOOL_OPEN_CLOSE',
        TOP_DOOR_ROTATE = 'TOP_DOOR_ROTATE',
        WHEEL_BASE_TRANSLATE_X = 'WHEEL_BASE_TRANSLATE_X',
        WORKING_WIDTH_TRANSLATE_X = 'WORKING_WIDTH_TRANSLATE_X',
    },
    NO_DATA = {
    },
    SEPARATOR = {
        ANY_INPUT = 3,
        COMBO_INPUT = 2,
        NONE = 1,
    },
}

function InputHelpElement.class() end
function InputHelpElement.copy() end
function InputHelpElement.getActionNames() end
function InputHelpElement.isa() end
function InputHelpElement.new() end
function InputHelpElement.superClass() end
