---@class ListElement
ListElement = {} -- empty

function ListElement.addElement() end
function ListElement.addElementAtPosition() end
function ListElement.applyElementSelection() end
function ListElement.applyListAspectScale() end
function ListElement.applyScreenAlignment() end
function ListElement.calculateFirstVisibleItem() end
function ListElement.canReceiveFocus() end
function ListElement.class() end
function ListElement.clearElementSelection() end
function ListElement.convertVisualRowColumToReal() end
function ListElement.copy() end
function ListElement.copyAttributes() end
function ListElement.delete() end
function ListElement.deleteListItems() end
function ListElement.getItemCount() end
function ListElement.getItemFactor() end
function ListElement.getItemIndexByRealRowColumn() end
function ListElement.getItemPosition() end
function ListElement.getNumOfColumns() end
function ListElement.getNumOfRows() end
function ListElement.getRealRowColumnByIndex() end
function ListElement.getRowColumnForScreenPosition() end
function ListElement.getSelectedElement() end
function ListElement.getSelectedElementIndex() end
function ListElement.getUnclampedIndexByRealRowColumn() end
function ListElement.getVisibleItemCount() end
function ListElement.isa() end
function ListElement.loadFromXML() end
function ListElement.loadProfile() end
function ListElement.mouseEvent() end
function ListElement.new() end
function ListElement.notifyClick() end
function ListElement.notifyDoubleClick() end
function ListElement.onFocusActivate() end
function ListElement.onFocusEnter() end
function ListElement.onFocusLeave() end
function ListElement.onGuiSetupFinished() end
function ListElement.onMouseDown() end
function ListElement.onMouseUp() end
function ListElement.onOpen() end
function ListElement.onSliderValueChanged() end
function ListElement.raiseSliderUpdateEvent() end
function ListElement.removeElement() end
function ListElement.scrollList() end
function ListElement.scrollTo() end
function ListElement.setSelectedIndex() end
function ListElement.setSelectionByRealRowAndColumn() end
function ListElement.shouldFocusChange() end
function ListElement.superClass() end
function ListElement.updateAbsolutePosition() end
function ListElement.updateAlternatingBackground() end
function ListElement.updateItemPositions() end
function ListElement.updateItemPositionsInRange() end
function ListElement.verifyConfiguration() end
function ListElement.verifyListItemConfiguration() end
