---@class Mission00
Mission00 = {} -- empty

function Mission00.addChatMessage() end
function Mission00.addLoadFinishedListener() end
function Mission00.canUnpauseGame() end
function Mission00.class() end
function Mission00.consoleRenderStoreIcons() end
function Mission00.copy() end
function Mission00.delete() end
function Mission00.doPauseGame() end
function Mission00.doUnpauseGame() end
function Mission00.draw() end
function Mission00.getIsTourSupported() end
function Mission00.isa() end
function Mission00.load() end
function Mission00.loadAdditionalFiles() end
function Mission00.loadCompetitiveMultiplayer() end
function Mission00.loadEconomy() end
function Mission00.loadEnvironment() end
function Mission00.loadHotspots() end
function Mission00.loadItems() end
function Mission00.loadItemsFinished() end
function Mission00.loadMission00Finished() end
function Mission00.loadOnCreateLoadedObjects() end
function Mission00.loadVehicles() end
function Mission00.loadVehiclesFinish() end
function Mission00.loadVehiclesLoadVehicleFinished() end
function Mission00.loadVehiclesStep() end
function Mission00.new() end
function Mission00.onCreateStartPoint() end
function Mission00.onStartMission() end
function Mission00.registerObjectToCallOnMissionStart() end
function Mission00.removeLoadFinishedListener() end
function Mission00.saveItems() end
function Mission00.saveOnCreateObjects() end
function Mission00.saveVehicleList() end
function Mission00.saveVehicles() end
function Mission00.scrollChatMessages() end
function Mission00.setLastChatMessageTime() end
function Mission00.setMissionInfo() end
function Mission00.superClass() end
function Mission00.update() end
