---@class ModHubController
ModHubController = {
    CATEGORY_ID_CONTEST = 8,
    CATEGORY_ID_DOWNLOAD = 1,
    CATEGORY_ID_UPDATE = 2,
}

function ModHubController.class() end
function ModHubController.copy() end
function ModHubController.endModification() end
function ModHubController.generateSearchScore() end
function ModHubController.getCategories() end
function ModHubController.getCategory() end
function ModHubController.getCategoryData() end
function ModHubController.getDependendMods() end
function ModHubController.getFreeModSpaceKb() end
function ModHubController.getModInfo() end
function ModHubController.getModsByCategory() end
function ModHubController.getPostFix() end
function ModHubController.getTotalFilesizeKb() end
function ModHubController.getVote() end
function ModHubController.install() end
function ModHubController.isCategorySearchable() end
function ModHubController.isContestEnabled() end
function ModHubController.isa() end
function ModHubController.load() end
function ModHubController.loadCategoriesFromXML() end
function ModHubController.new() end
function ModHubController.reload() end
function ModHubController.reset() end
function ModHubController.searchInCategory() end
function ModHubController.searchMods() end
function ModHubController.setAddedToDownloadCallback() end
function ModHubController.setDependendModIstallFailedCallback() end
function ModHubController.setDiscSpaceChangedCallback() end
function ModHubController.setModInstallFailedCallback() end
function ModHubController.setShowAllMods() end
function ModHubController.setUninstallFailedCallback() end
function ModHubController.setUninstalledCallback() end
function ModHubController.setVotedCallback() end
function ModHubController.startModification() end
function ModHubController.superClass() end
function ModHubController.uninstall() end
function ModHubController.update() end
function ModHubController.updateRecommendationSystem() end
function ModHubController.userProfileChanged() end
function ModHubController.vote() end
