---@class Motorized
Motorized = {
    DAMAGED_USAGE_INCREASE = 0.3,
}

function Motorized.actionEventToggleMotorState() end
function Motorized.addToPhysics() end
function Motorized.getAirConsumerUsage() end
function Motorized.getBrakeForce() end
function Motorized.getCanMotorRun() end
function Motorized.getCanStartAIVehicle() end
function Motorized.getConsumerFillUnitIndex() end
function Motorized.getDashboardSpeedDir() end
function Motorized.getDeactivateLightsOnLeave() end
function Motorized.getDeactivateOnLeave() end
function Motorized.getIsActiveForLights() end
function Motorized.getIsActiveForWipers() end
function Motorized.getIsDashboardGroupActive() end
function Motorized.getIsMotorStarted() end
function Motorized.getIsOperating() end
function Motorized.getMotor() end
function Motorized.getMotorBrakeTime() end
function Motorized.getMotorLoadPercentage() end
function Motorized.getMotorNotAllowedWarning() end
function Motorized.getMotorRpmPercentage() end
function Motorized.getMotorStartTime() end
function Motorized.getMotorType() end
function Motorized.getName() end
function Motorized.getSpecValueFuel() end
function Motorized.getSpecValueMaxSpeed() end
function Motorized.getSpecValuePower() end
function Motorized.getStopMotorOnLeave() end
function Motorized.getStoreAddtionalConfigData() end
function Motorized.initSpecialization() end
function Motorized.loadConsumerConfiguration() end
function Motorized.loadDashboardGroupFromXML() end
function Motorized.loadDifferentials() end
function Motorized.loadExhaustEffects() end
function Motorized.loadGears() end
function Motorized.loadMotor() end
function Motorized.loadSounds() end
function Motorized.loadSpecValueFuel() end
function Motorized.loadSpecValueMaxSpeed() end
function Motorized.loadSpecValuePower() end
function Motorized.onAIEnd() end
function Motorized.onDelete() end
function Motorized.onDraw() end
function Motorized.onEnterVehicle() end
function Motorized.onFillUnitFillLevelChanged() end
function Motorized.onLeaveVehicle() end
function Motorized.onLoad() end
function Motorized.onPostLoad() end
function Motorized.onReadStream() end
function Motorized.onReadUpdateStream() end
function Motorized.onRegisterActionEvents() end
function Motorized.onSetBroken() end
function Motorized.onUpdate() end
function Motorized.onUpdateTick() end
function Motorized.onWriteStream() end
function Motorized.onWriteUpdateStream() end
function Motorized.prerequisitesPresent() end
function Motorized.registerEventListeners() end
function Motorized.registerEvents() end
function Motorized.registerFunctions() end
function Motorized.registerOverwrittenFunctions() end
function Motorized.startMotor() end
function Motorized.stopMotor() end
function Motorized.updateConsumers() end
function Motorized.updateMotorProperties() end
function Motorized.updateMotorTemperature() end
