---@class Network
Network = {
    TYPE_APPLICATION = 0,
    TYPE_APPLICATION_UNCONNECTED = 26,
    TYPE_CONNECTION_ATTEMPT_FAILED = 2,
    TYPE_CONNECTION_BANNED = 9,
    TYPE_CONNECTION_LOST = 7,
    TYPE_CONNECTION_REQUEST_ACCEPTED = 1,
    TYPE_DISCONNECTION_NOTIFICATION = 6,
    TYPE_INVALID_PASSWORD = 10,
    TYPE_NEW_INCOMING_CONNECTION = 4,
    TYPE_NO_FREE_INCOMING_CONNECTIONS = 5,
    TYPE_PONG = 13,
    TYPE_RSA_PUBLIC_KEY_MISMATCH = 8,
}
