---@class ObjectIds
ObjectIds = {
    FARM = 66,
    MAX_OBJECT_ID = 65535,
    MISSION = 67,
    MISSION_BALE = 69,
    MISSION_CULTIVATE = 70,
    MISSION_FERTILIZE = 71,
    MISSION_FIELD = 68,
    MISSION_HARVEST = 72,
    MISSION_PLOW = 73,
    MISSION_SOW = 74,
    MISSION_SPRAY = 75,
    MISSION_TRANSPORT = 76,
    MISSION_WEED = 77,
    OBJECT_ANIMAL = 25,
    OBJECT_ANIMAL_CROWS_WILDLIFE = 24,
    OBJECT_ANIMAL_HUSBANDRY = 22,
    OBJECT_ANIMAL_LIGHT_WILDLIFE = 23,
    OBJECT_ANIMAL_LOADING_TRIGGER = 10,
    OBJECT_ANIMATED_MAP_OBJECT = 51,
    OBJECT_ANIMATED_OBJECT = 50,
    OBJECT_BALE = 6,
    OBJECT_BASKETBALL = 62,
    OBJECT_BEEHIVE_PLACEABLE = 37,
    OBJECT_BGA = 32,
    OBJECT_BGA_PLACEABLE = 57,
    OBJECT_BGA_SELLING_STATION = 17,
    OBJECT_BGA_TIP_TRIGGER = 33,
    OBJECT_BUNKERSILO_PLACEABLE = 58,
    OBJECT_BUNKER_SILO = 28,
    OBJECT_BUNKER_SILO_TIP_TRIGGER = 29,
    OBJECT_BUYING_STATION = 18,
    OBJECT_BUYING_STATION_PLACEABLE = 49,
    OBJECT_CHAINSAW = 60,
    OBJECT_DOG = 11,
    OBJECT_DOGBALL = 63,
    OBJECT_DOGHOUSE_PLACEABLE = 45,
    OBJECT_FARMHOUSE_PLACEABLE = 53,
    OBJECT_FILLLEVEL_LISTENER = 21,
    OBJECT_GREENHOUSE_PLACEABLE = 38,
    OBJECT_HANDTOOL = 59,
    OBJECT_HEATING_PLANT_PLACEABLE = 43,
    OBJECT_HIGHPRESSUREWASHERLANCE = 61,
    OBJECT_HIGHPRESSURE_WASHER_PLACEABLE = 39,
    OBJECT_HORSE = 26,
    OBJECT_LOADING_STATION = 19,
    OBJECT_LOAD_TRIGGER = 14,
    OBJECT_MISSION_PHYSICS_OBJECT = 9,
    OBJECT_MOUNTABLE_OBJECT = 5,
    OBJECT_OBJECT = 3,
    OBJECT_PHYSICS_OBJECT = 4,
    OBJECT_PLACEABLE = 34,
    OBJECT_PLAYER = 1,
    OBJECT_RAILROADVEHICLE = 31,
    OBJECT_RECIEVING_TIP_TRIGGER = 64,
    OBJECT_REFILLABLE_PLACEABLE = 54,
    OBJECT_RIDEABLE_ANIMAL = 27,
    OBJECT_SAPLING_PALLET = 8,
    OBJECT_SELLING_STATION = 16,
    OBJECT_SELLING_STATION_PLACEABLE = 48,
    OBJECT_SILO_EXTENSION_PLACEABLE = 41,
    OBJECT_SILO_PLACEABLE = 47,
    OBJECT_SILO_TRIGGER = 12,
    OBJECT_SOLAR_COLLECTOR_PLACEABLE = 36,
    OBJECT_STORAGE = 65,
    OBJECT_TRAIN = 30,
    OBJECT_TRAIN_PLACEABLE = 55,
    OBJECT_TREE = 7,
    OBJECT_TREE_PLACEABLE = 40,
    OBJECT_UNLOADING_STATION = 15,
    OBJECT_UNLOAD_FEEDING_TROUGH = 20,
    OBJECT_UNLOAD_TRIGGER = 13,
    OBJECT_VEHICLE = 2,
    OBJECT_VEHICLE_PLACEABLE = 52,
    OBJECT_WATERTOWER_PLACEABLE = 46,
    OBJECT_WIND_TURBINE_PLACEABLE = 35,
    OBJECT_WOOD_CRUSHER_PLACEABLE = 42,
    OBJECT_WOOD_SELL_STATION_PLACEABLE = 56,
    OBJECT_WORKSHOP_PLACEABLE = 44,
    SEND_NUM_BITS = 16,
    TRAFFIC_SYSTEM = 78,
    objectClasses = {
        FillTriggerPlaceable = {}, -- MAX_DEPTH -- FillTriggerPlaceable
    },
    objectIdNext = 140,
    objectIdToClass = {
        [1] = {}, -- MAX_DEPTH -- Player
        [55] = {}, -- MAX_DEPTH -- TrainPlaceable
        [53] = {}, -- MAX_DEPTH -- FarmhousePlaceable
        [52] = {}, -- MAX_DEPTH -- VehiclePlaceable
        [56] = {}, -- MAX_DEPTH -- WoodSellStationPlaceable
        [58] = {}, -- MAX_DEPTH -- BunkerSiloPlaceable
        [57] = {}, -- MAX_DEPTH -- BgaPlaceable
        [59] = {}, -- MAX_DEPTH -- HandTool
        [51] = {}, -- MAX_DEPTH -- AnimatedMapObject
        [49] = {}, -- MAX_DEPTH -- BuyingStationPlaceable
        [45] = {}, -- MAX_DEPTH -- Doghouse
        [44] = {}, -- MAX_DEPTH -- Workshop
        [50] = {}, -- MAX_DEPTH -- AnimatedObject
        [46] = {}, -- MAX_DEPTH -- WaterTower
        [48] = {}, -- MAX_DEPTH -- SellingStationPlaceable
        [47] = {}, -- MAX_DEPTH -- SiloPlaceable
        [43] = {}, -- MAX_DEPTH -- HeatingPlantPlaceable
        [60] = {}, -- MAX_DEPTH -- Chainsaw
        [62] = {}, -- MAX_DEPTH -- Basketball
        [74] = {}, -- MAX_DEPTH -- SowMission
        [73] = {}, -- MAX_DEPTH -- PlowMission
        [72] = {}, -- MAX_DEPTH -- HarvestMission
        [75] = {}, -- MAX_DEPTH -- SprayMission
        [77] = {}, -- MAX_DEPTH -- WeedMission
        [76] = {}, -- MAX_DEPTH -- TransportMission
        [61] = {}, -- MAX_DEPTH -- HighPressureWasherLance
        [71] = {}, -- MAX_DEPTH -- FertilizeMission
        [69] = {}, -- MAX_DEPTH -- BaleMission
        [65] = {}, -- MAX_DEPTH -- Storage
        [63] = {}, -- MAX_DEPTH -- DogBall
        [70] = {}, -- MAX_DEPTH -- CultivateMission
        [66] = {}, -- MAX_DEPTH -- Farm
        [68] = {}, -- MAX_DEPTH -- AbstractFieldMission
        [67] = {}, -- MAX_DEPTH -- AbstractMission
        [78] = {}, -- MAX_DEPTH -- TrafficSystem
        [42] = {}, -- MAX_DEPTH -- WoodCrusherPlaceable
        [40] = {}, -- MAX_DEPTH -- TreePlaceable
        [15] = {}, -- MAX_DEPTH -- UnloadingStation
        [14] = {}, -- MAX_DEPTH -- LoadTrigger
        [13] = {}, -- MAX_DEPTH -- UnloadTrigger
        [16] = {}, -- MAX_DEPTH -- SellingStation
        [18] = {}, -- MAX_DEPTH -- BuyingStation
        [17] = {}, -- MAX_DEPTH -- BgaSellStation
        [19] = {}, -- MAX_DEPTH -- LoadingStation
        [11] = {}, -- MAX_DEPTH -- Dog
        [9] = {}, -- MAX_DEPTH -- MissionPhysicsObject
        [3] = {}, -- MAX_DEPTH -- Object
        [2] = {}, -- MAX_DEPTH -- Vehicle
        [10] = {}, -- MAX_DEPTH -- AnimalLoadingTrigger
        [4] = {}, -- MAX_DEPTH -- PhysicsObject
        [6] = {}, -- MAX_DEPTH -- Bale
        [5] = {}, -- MAX_DEPTH -- MountableObject
        [41] = {}, -- MAX_DEPTH -- SiloExtensionPlaceable
        [20] = {}, -- MAX_DEPTH -- UnloadFeedingTrough
        [22] = {}, -- MAX_DEPTH -- AnimalHusbandry
        [36] = {}, -- MAX_DEPTH -- SolarCollectorPlaceable
        [35] = {}, -- MAX_DEPTH -- WindTurbinePlaceable
        [34] = {}, -- MAX_DEPTH -- Placeable
        [37] = {}, -- MAX_DEPTH -- BeehivePlaceable
        [39] = {}, -- MAX_DEPTH -- HighPressureWasher
        [38] = {}, -- MAX_DEPTH -- GreenhousePlaceable
        [21] = {}, -- MAX_DEPTH -- FillLevelListener
        [32] = {}, -- MAX_DEPTH -- Bga
        [28] = {}, -- MAX_DEPTH -- BunkerSilo
        [24] = {}, -- MAX_DEPTH -- CrowsWildlife
        [23] = {}, -- MAX_DEPTH -- LightWildlife
        [31] = {}, -- MAX_DEPTH -- RailroadVehicle
        [25] = {}, -- MAX_DEPTH -- Animal
        [27] = {}, -- MAX_DEPTH -- RideableAnimal
        [26] = {}, -- MAX_DEPTH -- Horse
        [139] = {}, -- MAX_DEPTH -- FillTriggerPlaceable
    },
    objectIdsUsed = {
        [1] = true,
        [55] = true,
        [53] = true,
        [52] = true,
        [56] = true,
        [58] = true,
        [57] = true,
        [59] = true,
        [51] = true,
        [49] = true,
        [45] = true,
        [44] = true,
        [50] = true,
        [46] = true,
        [48] = true,
        [47] = true,
        [43] = true,
        [60] = true,
        [62] = true,
        [74] = true,
        [73] = true,
        [72] = true,
        [75] = true,
        [77] = true,
        [76] = true,
        [61] = true,
        [71] = true,
        [69] = true,
        [65] = true,
        [63] = true,
        [70] = true,
        [66] = true,
        [68] = true,
        [67] = true,
        [78] = true,
        [42] = true,
        [40] = true,
        [15] = true,
        [14] = true,
        [13] = true,
        [16] = true,
        [18] = true,
        [17] = true,
        [19] = true,
        [11] = true,
        [9] = true,
        [3] = true,
        [2] = true,
        [10] = true,
        [4] = true,
        [6] = true,
        [5] = true,
        [41] = true,
        [20] = true,
        [22] = true,
        [36] = true,
        [35] = true,
        [34] = true,
        [37] = true,
        [39] = true,
        [38] = true,
        [21] = true,
        [32] = true,
        [28] = true,
        [24] = true,
        [23] = true,
        [31] = true,
        [25] = true,
        [27] = true,
        [26] = true,
        [139] = true,
    },
}

function ObjectIds.assignObjectClassId() end
function ObjectIds.assignObjectClassIds() end
function ObjectIds.assignObjectClassObjectId() end
function ObjectIds.getObjectClassById() end
function ObjectIds.getObjectClassByName() end
