---@class PowerTakeOffs
PowerTakeOffs = {} -- empty

function PowerTakeOffs.attachPowerTakeOff() end
function PowerTakeOffs.attachTypedPowerTakeOff() end
function PowerTakeOffs.detachPowerTakeOff() end
function PowerTakeOffs.detachTypedPowerTakeOff() end
function PowerTakeOffs.getInputPowerTakeOffs() end
function PowerTakeOffs.getInputPowerTakeOffsByJointDescIndexAndName() end
function PowerTakeOffs.getIsPowerTakeOffActive() end
function PowerTakeOffs.getOutputPowerTakeOffs() end
function PowerTakeOffs.getOutputPowerTakeOffsByJointDescIndex() end
function PowerTakeOffs.initSpecialization() end
function PowerTakeOffs.loadBasicPowerTakeOff() end
function PowerTakeOffs.loadDoubleJointPowerTakeOff() end
function PowerTakeOffs.loadExtraDependentParts() end
function PowerTakeOffs.loadInputPowerTakeOff() end
function PowerTakeOffs.loadLocalPowerTakeOff() end
function PowerTakeOffs.loadOutputPowerTakeOff() end
function PowerTakeOffs.loadPowerTakeOffFromConfigFile() end
function PowerTakeOffs.loadSingleJointPowerTakeOff() end
function PowerTakeOffs.onDelete() end
function PowerTakeOffs.onLoad() end
function PowerTakeOffs.onLoadFinished() end
function PowerTakeOffs.onPostAttachImplement() end
function PowerTakeOffs.onPostLoad() end
function PowerTakeOffs.onPreAttachImplement() end
function PowerTakeOffs.onPreDetachImplement() end
function PowerTakeOffs.onUpdateInterpolation() end
function PowerTakeOffs.parkPowerTakeOff() end
function PowerTakeOffs.placeLocalPowerTakeOff() end
function PowerTakeOffs.prerequisitesPresent() end
function PowerTakeOffs.registerEventListeners() end
function PowerTakeOffs.registerFunctions() end
function PowerTakeOffs.registerOverwrittenFunctions() end
function PowerTakeOffs.updateAttachedPowerTakeOffs() end
function PowerTakeOffs.updateDistanceOfTypedPowerTakeOff() end
function PowerTakeOffs.updateDoubleJointPowerTakeOff() end
function PowerTakeOffs.updateExtraDependentParts() end
function PowerTakeOffs.updatePowerTakeOff() end
function PowerTakeOffs.updatePowerTakeOffLength() end
function PowerTakeOffs.updateSingleJointPowerTakeOff() end
function PowerTakeOffs.validatePowerTakeOffAttachment() end
