---@class RenderText
RenderText = {
    ALIGN_CENTER = 1,
    ALIGN_LEFT = 0,
    ALIGN_RIGHT = 2,
    DEFAULT_LINE_HEIGHT_SCALE = 1.1000000238419,
    VERTICAL_ALIGN_BASELINE = 0,
    VERTICAL_ALIGN_BOTTOM = 3,
    VERTICAL_ALIGN_MIDDLE = 2,
    VERTICAL_ALIGN_TOP = 1,
}
