---@class Reverb
Reverb = {
    CITY = 4,
    FACTORY_HALL = 8,
    FACTORY_LARGEROOM = 7,
    FACTORY_MEDIUMROOM = 6,
    FACTORY_SHORTPASSAGE = 5,
    FACTORY_SMALLROOM = 9,
    FOREST = 2,
    GENERIC = 0,
    HANGAR = 1,
    PARKINGLOT = 3,
}
