---@class Savegame
Savegame = {
    ERROR_BAD_INDEX = 4,
    ERROR_CANCELLED = 1,
    ERROR_CLOUD_CONFLICT = 12,
    ERROR_DATA_CORRUPT = 3,
    ERROR_DEVICE_UNAVAILABLE = 2,
    ERROR_LOAD_FAILED = 9,
    ERROR_LOAD_INVALID_USER = 10,
    ERROR_OK = 0,
    ERROR_OPERATION_IN_PROGRESS = 11,
    ERROR_QUOTA_EXCEEDED = 14,
    ERROR_RESOLVE_FAILED = 13,
    ERROR_SAVE_FAILED = 7,
    ERROR_SAVE_NO_SPACE = 8,
    ERROR_SCAN_FAILED = 5,
    ERROR_SCAN_IN_PROGRESS = 6,
}
