---@class SettingsAdvancedFrame
SettingsAdvancedFrame = {
    CONTROLS = {
        ELEMENT_FOLIAGE_DRAW_DISTANCE = 'foliageDrawDistanceElement',
        ELEMENT_LIGHTS_PROFILE = 'lightsProfileElement',
        ELEMENT_LOD_DISTANCE = 'lodDistanceElement',
        ELEMENT_MAX_LIGHTS = 'maxLightsElement',
        ELEMENT_MAX_MIRRORS = 'maxMirrorsElement',
        ELEMENT_MAX_TIRE_TRACKS = 'maxTireTracksElement',
        ELEMENT_MSAA = 'msaaElement',
        ELEMENT_OBJECT_DRAW_DISTANCE = 'objectDrawDistanceElement',
        ELEMENT_PERFORMANCE_CLASS = 'performanceClassElement',
        ELEMENT_REAL_BEACON_LIGHTS = 'realBeaconLightsElement',
        ELEMENT_SHADER_QUALITY = 'shaderQualityElement',
        ELEMENT_SHADOW_MAP_FILTERING = 'shadowMapFilteringElement',
        ELEMENT_SHADOW_QUALITY = 'shadowQualityElement',
        ELEMENT_TERRAIN_LOD_DISTANCE = 'terrainLODDistanceElement',
        ELEMENT_TERRAIN_QUALITY = 'terrainQualityElement',
        ELEMENT_TEXTURE_FILTERING = 'textureFilteringElement',
        ELEMENT_TEXTURE_RESOLUTION = 'textureResolutionElement',
        ELEMENT_VOLUME_MESH_TESSELLATION = 'volumeMeshTessellationElement',
        MAIN_CONTAINER = 'settingsContainer',
    },
    L10N_SYMBOL = {
        BUTTON_APPLY = 'button_apply',
    },
}

function SettingsAdvancedFrame.class() end
function SettingsAdvancedFrame.copy() end
function SettingsAdvancedFrame.copyAttributes() end
function SettingsAdvancedFrame.getMainElementPosition() end
function SettingsAdvancedFrame.getMainElementSize() end
function SettingsAdvancedFrame.getMenuButtonInfo() end
function SettingsAdvancedFrame.initialize() end
function SettingsAdvancedFrame.isa() end
function SettingsAdvancedFrame.new() end
function SettingsAdvancedFrame.onApplySettings() end
function SettingsAdvancedFrame.onClickFoliageDrawDistance() end
function SettingsAdvancedFrame.onClickLODDistance() end
function SettingsAdvancedFrame.onClickLightsProfile() end
function SettingsAdvancedFrame.onClickMSAA() end
function SettingsAdvancedFrame.onClickMaxMirrors() end
function SettingsAdvancedFrame.onClickMaxTireTracks() end
function SettingsAdvancedFrame.onClickObjectDrawDistance() end
function SettingsAdvancedFrame.onClickPerformanceClass() end
function SettingsAdvancedFrame.onClickRealBeaconLights() end
function SettingsAdvancedFrame.onClickShaderQuality() end
function SettingsAdvancedFrame.onClickShadowMapFiltering() end
function SettingsAdvancedFrame.onClickShadowMaxLights() end
function SettingsAdvancedFrame.onClickShadowQuality() end
function SettingsAdvancedFrame.onClickTerrainLODDistance() end
function SettingsAdvancedFrame.onClickTerrainQuality() end
function SettingsAdvancedFrame.onClickTextureFiltering() end
function SettingsAdvancedFrame.onClickTextureResolution() end
function SettingsAdvancedFrame.onClickVolumeMeshTessellation() end
function SettingsAdvancedFrame.onCreateFoliageDrawDistance() end
function SettingsAdvancedFrame.onCreateLODDistance() end
function SettingsAdvancedFrame.onCreateLightsProfile() end
function SettingsAdvancedFrame.onCreateMSAA() end
function SettingsAdvancedFrame.onCreateMaxMirrors() end
function SettingsAdvancedFrame.onCreateMaxTireTracks() end
function SettingsAdvancedFrame.onCreateObjectDrawDistance() end
function SettingsAdvancedFrame.onCreatePerformanceClass() end
function SettingsAdvancedFrame.onCreateShaderQuality() end
function SettingsAdvancedFrame.onCreateShadowMapFiltering() end
function SettingsAdvancedFrame.onCreateShadowMaxLights() end
function SettingsAdvancedFrame.onCreateShadowQuality() end
function SettingsAdvancedFrame.onCreateTerrainLODDistance() end
function SettingsAdvancedFrame.onCreateTerrainQuality() end
function SettingsAdvancedFrame.onCreateTextureFiltering() end
function SettingsAdvancedFrame.onCreateTextureResolution() end
function SettingsAdvancedFrame.onCreateVolumeMeshTessellation() end
function SettingsAdvancedFrame.onFrameOpen() end
function SettingsAdvancedFrame.superClass() end
function SettingsAdvancedFrame.updatePerformanceClass() end
function SettingsAdvancedFrame.updateValues() end
