---@class ShopConfigScreen
ShopConfigScreen = {
    CAMERA_MAX_DISTANCE_FACTOR = 3,
    CAMERA_MIN_DISTANCE_FACTOR = 0.8,
    CAMERA_MIN_DISTANCE_TO_X_OFFSET_FACTOR = 0.15,
    CONTROLS = {
        ATTRIBUTE_ICONS = 'attrIcon',
        ATTRIBUTE_VALUES = 'attrValue',
        BRAND_ICON = 'shopConfigBrandIcon',
        BUTTONS = 'buttonsPC',
        BUYING_BASE_PRICE = 'basePriceText',
        BUYING_TOTAL_PRICE = 'totalPriceText',
        BUYING_UPGRADES_PRICE = 'upgradesPriceText',
        BUY_BUTTON = 'buyButton',
        CHANGE_COLOR_BUTTON = 'changeColorButton',
        COLOR_IMAGES = 'colorImage',
        COLOR_NAMES = 'colorName',
        COLOR_PICKER_BUTTONS = 'colorPicker',
        COLOR_PRICES = 'colorPrice',
        CONFIG_NAMES = 'configName',
        CONFIG_OPTIONS = 'configOption',
        CONFIG_PRICES = 'configPrice',
        CONFIG_SLIDER = 'configSlider',
        CONFIG_SLIDER_BACKGROUND = 'configSliderBackground',
        CONFIG_SLIDER_BOX = 'configSliderBox',
        CONTENT = 'shopConfigContent',
        ITEM_NAME = 'shopConfigItemName',
        LEASE_BUTTON = 'leaseButton',
        LEASING_BASE_COST = 'costsBaseText',
        LEASING_COST_PER_DAY = 'costsPerDayText',
        LEASING_COST_PER_HOUR = 'costsPerOperatingHourText',
        LEASING_INITIAL_COST = 'initialCostsText',
        LEFT_CONFIG_BOX = 'leftConfigBox',
        LOADING_ANIMATION = 'loadingAnimation',
        MONEY_BOX = 'shopMoneyBox',
        MONEY_TEXT = 'shopMoney',
        ROTATE_INPUT_GLYPH_FRAME = 'rotateInputGlyphFrame',
        ZOOM_INPUT_GLYPH_FRAME = 'zoomInputGlyphFrame',
    },
    FADE_TEXTURE_PATH = 'dataS/scripts/shared/graph_pixel.png',
    FAR_BLUR_END_DISTANCE = 100,
    GUI_PROFILE = {
        BUTTON_BUY = 'buttonBuy',
        BUTTON_CONFIGURE = 'buttonConfigurate',
        CAPACITY = 'shopListAttributeIconCapacity',
        FUEL = 'shopListAttributeIconFuel',
        MAINTENANCE_COST = 'shopListAttributeIconMaintenanceCosts',
        MAX_SPEED = 'shopListAttributeIconMaxSpeed',
        POWER = 'shopListAttributeIconPower',
        POWER_REQUIREMENT = 'shopListAttributeIconPowerReq',
        SHOP_MONEY = 'shopMoney',
        SHOP_MONEY_NEGATIVE = 'shopMoneyNeg',
        WORKING_SPEED = 'shopListAttributeIconWorkSpeed',
        WORKING_WIDTH = 'shopListAttributeIconWorkingWidth',
    },
    INITIAL_CAMERA_ROTATION = {
        [1] = 0,
        [2] = -140,
        [3] = 0,
    },
    INPUT_CONTEXT_NAME = 'MENU_SHOP_CONFIG',
    L10N_SYMBOL = {
        BUTTON_BUY = 'button_buy',
        BUTTON_CONFIGURE = 'button_configurate',
        CAPACITY = 'shop_capacityValue',
        CONFIGURATION_LABEL = 'shop_configuration',
        CONFIRM_BUY = 'shop_doYouWantToBuy',
        CONFIRM_LEASE = 'shop_doYouWantToLease',
        DEF_SHORT = 'fillType_def_short',
        FUEL = 'shop_fuelValue',
        FUEL_DEF = 'shop_fuelDefValue',
        MAINTENANCE_COST = 'shop_maintenanceValue',
        MAX_SPEED = 'shop_maxSpeed',
        NOT_ENOUGH_MONEY_BUY = 'shop_messageNotEnoughMoneyToBuy',
        NOT_ENOUGH_MONEY_LEASE = 'shop_messageNotEnoughMoneyToLease',
        POWER = 'shop_maxPowerValue',
        POWER_REQUIREMENT = 'shop_neededPowerValue',
        TOO_FEW_SLOTS = 'shop_messageNotEnoughSlotsToBuy',
        UNIT_LITER = 'unit_literShort',
        WORKING_SPEED = 'shop_maxSpeed',
        WORKING_WIDTH = 'shop_workingWidthValue',
    },
    MAX_CAMERA_DISTANCE = 13.5,
    MAX_CAMERA_HEIGHT = 11,
    MIN_MOUSE_DRAG_INPUT = 1.5,
    MOUSE_SPEED_MULTIPLIER = 2,
    NEAR_CLIP_DISTANCE = 0.2,
    NO_VEHICLE = {

        delete = function () end,
    },
    SIZE = {
        INPUT_GLYPH = {
            [1] = 48,
            [2] = 48,
        },
    },
    STORE_ITEM_FILL_UNIT_CONFIG = 'fillUnit',
    STORE_ITEM_MOTOR_CONFIG = 'motor',
    WORKSHOP_PATH = '$data/maps/textures/shared/uiStore.i3d',
}

function ShopConfigScreen.class() end
function ShopConfigScreen.copy() end
function ShopConfigScreen.createCamera() end
function ShopConfigScreen.createFadeAnimations() end
function ShopConfigScreen.createInputGlyphs() end
function ShopConfigScreen.createWorkshop() end
function ShopConfigScreen.delete() end
function ShopConfigScreen.deletePreviewVehicles() end
function ShopConfigScreen.disableAlternateBindings() end
function ShopConfigScreen.disableUnusedOptions() end
function ShopConfigScreen.draw() end
function ShopConfigScreen.fadeScreen() end
function ShopConfigScreen.getConfigurationCostsAndChanges() end
function ShopConfigScreen.getDefaultConfigurationColorIndex() end
function ShopConfigScreen.isa() end
function ShopConfigScreen.limitXRotation() end
function ShopConfigScreen.loadCurrentConfiguration() end
function ShopConfigScreen.loadMapData() end
function ShopConfigScreen.makeOptionFocusOverrideBottomNoScrolling() end
function ShopConfigScreen.makeOptionFocusOverrideBottomScrolling() end
function ShopConfigScreen.makeOptionFocusOverrideTopNoScrolling() end
function ShopConfigScreen.makeOptionFocusOverrideTopScrolling() end
function ShopConfigScreen.new() end
function ShopConfigScreen.onCallback() end
function ShopConfigScreen.onCameraLeftRight() end
function ShopConfigScreen.onCameraUpDown() end
function ShopConfigScreen.onCameraZoom() end
function ShopConfigScreen.onClickActivate() end
function ShopConfigScreen.onClickCancel() end
function ShopConfigScreen.onClickOk() end
function ShopConfigScreen.onClickShop() end
function ShopConfigScreen.onClose() end
function ShopConfigScreen.onFocusColorButton() end
function ShopConfigScreen.onGuiSetupFinished() end
function ShopConfigScreen.onLeaveColorButton() end
function ShopConfigScreen.onOpen() end
function ShopConfigScreen.onPickColor() end
function ShopConfigScreen.onSliderChanged() end
function ShopConfigScreen.onVehicleBought() end
function ShopConfigScreen.onVehicleLoaded() end
function ShopConfigScreen.onYesNoBuy() end
function ShopConfigScreen.onYesNoLease() end
function ShopConfigScreen.overrideOptionFocus() end
function ShopConfigScreen.processAttributeData() end
function ShopConfigScreen.processStoreItemCapacity() end
function ShopConfigScreen.processStoreItemColorOption() end
function ShopConfigScreen.processStoreItemConfigurationOption() end
function ShopConfigScreen.processStoreItemConfigurationSet() end
function ShopConfigScreen.processStoreItemConfigurations() end
function ShopConfigScreen.processStoreItemFuelCapacity() end
function ShopConfigScreen.processStoreItemMaxSpeed() end
function ShopConfigScreen.processStoreItemPowerNeeded() end
function ShopConfigScreen.processStoreItemPowerOutput() end
function ShopConfigScreen.processStoreItemSubConfigurationOption() end
function ShopConfigScreen.processStoreItemUpkeep() end
function ShopConfigScreen.processStoreItemWorkingSpeed() end
function ShopConfigScreen.processStoreItemWorkingWidth() end
function ShopConfigScreen.registerInputActions() end
function ShopConfigScreen.resetCamera() end
function ShopConfigScreen.selectFirstConfig() end
function ShopConfigScreen.setCallbacks() end
function ShopConfigScreen.setConfigPrice() end
function ShopConfigScreen.setCurrentMission() end
function ShopConfigScreen.setEconomyManager() end
function ShopConfigScreen.setRequestExitCallback() end
function ShopConfigScreen.setStoreItem() end
function ShopConfigScreen.setWorkshopNode() end
function ShopConfigScreen.setWorkshopWorldPosition() end
function ShopConfigScreen.shouldFocusChange() end
function ShopConfigScreen.superClass() end
function ShopConfigScreen.toggleHUDVisible() end
function ShopConfigScreen.unloadMapData() end
function ShopConfigScreen.update() end
function ShopConfigScreen.updateBalanceText() end
function ShopConfigScreen.updateButtons() end
function ShopConfigScreen.updateCamera() end
function ShopConfigScreen.updateColorButton() end
function ShopConfigScreen.updateConfigOptionElement() end
function ShopConfigScreen.updateConfigOptionsData() end
function ShopConfigScreen.updateConfigOptionsDisplay() end
function ShopConfigScreen.updateConfigOptionsNavigation() end
function ShopConfigScreen.updateConfigSetOptionElement() end
function ShopConfigScreen.updateData() end
function ShopConfigScreen.updateDepthOfField() end
function ShopConfigScreen.updateDisplay() end
function ShopConfigScreen.updateInput() end
function ShopConfigScreen.updateInputContext() end
function ShopConfigScreen.updateInputGlyphs() end
function ShopConfigScreen.updatePriceData() end
function ShopConfigScreen.updateSlider() end
function ShopConfigScreen.updateSubConfigOptionElement() end
