---@class Trailer
Trailer = {
    TIPSTATE_CLOSED = 0,
    TIPSTATE_CLOSING = 3,
    TIPSTATE_OPEN = 2,
    TIPSTATE_OPENING = 1,
    TIP_SIDE_NUM_BITS = 3,
}

function Trailer.actionEventToggleTipSide() end
function Trailer.endTipping() end
function Trailer.getCanBeSelected() end
function Trailer.getCanDischargeToGround() end
function Trailer.getCanTogglePreferdTipSide() end
function Trailer.getDischargeNodeEmptyFactor() end
function Trailer.getIsNextCoverStateAllowed() end
function Trailer.getTipState() end
function Trailer.initSpecialization() end
function Trailer.initializeAnimationPart() end
function Trailer.loadAnimationPart() end
function Trailer.loadTipSide() end
function Trailer.onDelete() end
function Trailer.onDischargeStateChanged() end
function Trailer.onLoad() end
function Trailer.onReadStream() end
function Trailer.onRegisterActionEvents() end
function Trailer.onUpdate() end
function Trailer.onWriteStream() end
function Trailer.postInitializeAnimationPart() end
function Trailer.prerequisitesPresent() end
function Trailer.registerEventListeners() end
function Trailer.registerEvents() end
function Trailer.registerFunctions() end
function Trailer.registerOverwrittenFunctions() end
function Trailer.resetAnimationPartValues() end
function Trailer.saveToXMLFile() end
function Trailer.setPreferedTipSide() end
function Trailer.startTipping() end
function Trailer.stopTipping() end
function Trailer.updateAnimationPart() end
