---@class TreePlanter
TreePlanter = {} -- empty

function TreePlanter.actionEventToggleTreePlanterFieldLimitation() end
function TreePlanter.addNodeObjectMapping() end
function TreePlanter.createTree() end
function TreePlanter.doCheckSpeedLimit() end
function TreePlanter.getCanBeSelected() end
function TreePlanter.getDefaultSpeedLimit() end
function TreePlanter.getDirtMultiplier() end
function TreePlanter.getIsOnField() end
function TreePlanter.getIsSpeedRotatingPartActive() end
function TreePlanter.getIsWorkAreaActive() end
function TreePlanter.getSaplingPalletInRange() end
function TreePlanter.getWearMultiplier() end
function TreePlanter.loadPallet() end
function TreePlanter.onDelete() end
function TreePlanter.onDeleteTreePlanterObject() end
function TreePlanter.onDraw() end
function TreePlanter.onFillUnitFillLevelChanged() end
function TreePlanter.onLoad() end
function TreePlanter.onReadStream() end
function TreePlanter.onReadUpdateStream() end
function TreePlanter.onRegisterActionEvents() end
function TreePlanter.onTurnedOff() end
function TreePlanter.onTurnedOn() end
function TreePlanter.onUpdate() end
function TreePlanter.onUpdateTick() end
function TreePlanter.onWriteStream() end
function TreePlanter.onWriteUpdateStream() end
function TreePlanter.palletTriggerCallback() end
function TreePlanter.prerequisitesPresent() end
function TreePlanter.registerEventListeners() end
function TreePlanter.registerFunctions() end
function TreePlanter.registerOverwrittenFunctions() end
function TreePlanter.removeMountedObject() end
function TreePlanter.removeNodeObjectMapping() end
function TreePlanter.saveToXMLFile() end
function TreePlanter.setPlantLimitToField() end
