---@class TurnOnVehicle
TurnOnVehicle = {} -- empty

function TurnOnVehicle.actionEventTurnOn() end
function TurnOnVehicle.getAIRequiresTurnOffOnHeadland() end
function TurnOnVehicle.getAIRequiresTurnOn() end
function TurnOnVehicle.getAlarmTriggerIsActive() end
function TurnOnVehicle.getCanAIImplementContinueWork() end
function TurnOnVehicle.getCanBeSelected() end
function TurnOnVehicle.getCanBeTurnedOn() end
function TurnOnVehicle.getCanToggleTurnedOn() end
function TurnOnVehicle.getIsFillUnitActive() end
function TurnOnVehicle.getIsOperating() end
function TurnOnVehicle.getIsPowerTakeOffActive() end
function TurnOnVehicle.getIsSeedChangeAllowed() end
function TurnOnVehicle.getIsTurnedOn() end
function TurnOnVehicle.getIsWorkAreaActive() end
function TurnOnVehicle.getShovelNodeIsActive() end
function TurnOnVehicle.getTurnedOnNotAllowedWarning() end
function TurnOnVehicle.loadAlarmTrigger() end
function TurnOnVehicle.loadInputAttacherJoint() end
function TurnOnVehicle.loadShovelNode() end
function TurnOnVehicle.loadWorkAreaFromXML() end
function TurnOnVehicle.onAIImplementBlock() end
function TurnOnVehicle.onAIImplementContinue() end
function TurnOnVehicle.onAIImplementEnd() end
function TurnOnVehicle.onAIImplementEndLine() end
function TurnOnVehicle.onAIImplementStart() end
function TurnOnVehicle.onAIImplementStartLine() end
function TurnOnVehicle.onAlarmTriggerChanged() end
function TurnOnVehicle.onDeactivate() end
function TurnOnVehicle.onDelete() end
function TurnOnVehicle.onLoad() end
function TurnOnVehicle.onPostAttach() end
function TurnOnVehicle.onPreDetach() end
function TurnOnVehicle.onReadStream() end
function TurnOnVehicle.onRegisterActionEvents() end
function TurnOnVehicle.onSetBroken() end
function TurnOnVehicle.onStateChange() end
function TurnOnVehicle.onTurnedOff() end
function TurnOnVehicle.onTurnedOn() end
function TurnOnVehicle.onUpdate() end
function TurnOnVehicle.onUpdateTick() end
function TurnOnVehicle.onWriteStream() end
function TurnOnVehicle.prerequisitesPresent() end
function TurnOnVehicle.registerEventListeners() end
function TurnOnVehicle.registerEvents() end
function TurnOnVehicle.registerFunctions() end
function TurnOnVehicle.registerOverwrittenFunctions() end
function TurnOnVehicle.setIsTurnedOn() end
