---@class WorkAreaType
WorkAreaType = {
    AUXILIARY = 5,
    BALER = 10,
    COMBINECHOPPER = 7,
    COMBINESWATH = 8,
    CULTIVATOR = 12,
    CUTTER = 15,
    DEFAULT = 4,
    FORAGEWAGON = 6,
    FRUITPREPARER = 9,
    MOWER = 11,
    PLOW = 3,
    RIDGEMARKER = 1,
    ROLLER = 18,
    SOWINGMACHINE = 14,
    SPRAYER = 13,
    TEDDER = 17,
    WEEDER = 2,
    WINDROWER = 16,
}
