---@class VehicleMotor
VehicleMotor = {
    DAMAGE_TORQUE_REDUCTION = 0.3,
}

function VehicleMotor.calculatePhysicalMaximumBackwardSpeed() end
function VehicleMotor.calculatePhysicalMaximumForwardSpeed() end
function VehicleMotor.calculatePhysicalMaximumSpeed() end
function VehicleMotor.class() end
function VehicleMotor.copy() end
function VehicleMotor.findGearChangeTargetGear() end
function VehicleMotor.findGearChangeTargetGearPrediction() end
function VehicleMotor.getAccelerationLimit() end
function VehicleMotor.getBestGear() end
function VehicleMotor.getBestGearRatio() end
function VehicleMotor.getBrakeForce() end
function VehicleMotor.getClutchRotSpeed() end
function VehicleMotor.getCurMaxRpm() end
function VehicleMotor.getDampingRateFullThrottle() end
function VehicleMotor.getDampingRateZeroThrottleClutchDisengaged() end
function VehicleMotor.getDampingRateZeroThrottleClutchEngaged() end
function VehicleMotor.getEqualizedMotorRpm() end
function VehicleMotor.getGearRatio() end
function VehicleMotor.getLastMotorRpm() end
function VehicleMotor.getLastRealMotorRpm() end
function VehicleMotor.getMaxClutchTorque() end
function VehicleMotor.getMaxRpm() end
function VehicleMotor.getMaximumBackwardSpeed() end
function VehicleMotor.getMaximumForwardSpeed() end
function VehicleMotor.getMinMaxGearRatio() end
function VehicleMotor.getMinRpm() end
function VehicleMotor.getMotorAppliedTorque() end
function VehicleMotor.getMotorAvailableTorque() end
function VehicleMotor.getMotorExternalTorque() end
function VehicleMotor.getMotorRotSpeed() end
function VehicleMotor.getMotorRotationAccelerationLimit() end
function VehicleMotor.getNonClampedMotorRpm() end
function VehicleMotor.getPeakTorque() end
function VehicleMotor.getPtoMotorRpmRatio() end
function VehicleMotor.getRequiredMotorRpmRange() end
function VehicleMotor.getRotInertia() end
function VehicleMotor.getSpeedLimit() end
function VehicleMotor.getTorque() end
function VehicleMotor.getTorqueAndSpeedValues() end
function VehicleMotor.getTorqueCurve() end
function VehicleMotor.getTorqueCurveValue() end
function VehicleMotor.isa() end
function VehicleMotor.new() end
function VehicleMotor.setAccelerationLimit() end
function VehicleMotor.setAutoGearChangeTime() end
function VehicleMotor.setDampingRateFullThrottle() end
function VehicleMotor.setDampingRateZeroThrottleClutchDisengaged() end
function VehicleMotor.setDampingRateZeroThrottleClutchEngaged() end
function VehicleMotor.setEqualizedMotorRpm() end
function VehicleMotor.setGearChangeTime() end
function VehicleMotor.setLastRpm() end
function VehicleMotor.setLowBrakeForce() end
function VehicleMotor.setMotorRotationAccelerationLimit() end
function VehicleMotor.setRotInertia() end
function VehicleMotor.setRpmLimit() end
function VehicleMotor.setSpeedLimit() end
function VehicleMotor.superClass() end
function VehicleMotor.update() end
function VehicleMotor.updateGear() end
